% PE_simulation_diff_1Dot_occlusion_v1.m
%
% Purpose:
%   Run the one-dot PE dRSA pipeline for the occlusion paradigm generated by
%   experiment/stimuli_generation_v18.m.
%   Matrix plots include dotted horizontal/vertical guide lines at:
%     - full disappearance (occlusion_complete_frame)
%     - first reappearance frame (occlusion_end_frame / reappearance_start_frame)
%
% Canonical PE definition used in this script:
%   PE_signal = observed_signal - predicted_signal
%
% One-dot scope and design:
%   - Input trials must be single-dot (xy columns [x y]).
%   - Any two-dot-like input (xy columns >= 4) raises an explicit error.
%   - Run two occlusion conditions only:
%       * occluded_nondeviant
%       * occluded_deviant
%   - Keep deviant-only PE branch with signal-level PE and three neural targets:
%       a) neuralPE        = observed neural signal - predicted neural signal
%       b) neuralPredicted = predicted neural signal
%       c) neuralObserved  = observed neural signal
%   - Standard models include only:
%       1) observed position dot1
%       2) observed direction dot1
%   - Predicted models include only:
%       3) predicted position dot1
%       4) predicted direction dot1
%   - PE models include only:
%       1) PE position dot1
%       2) PE direction dot1
%   - dRSA mode remains selectable via dRSAtypeToRun ('corr' or 'PCR').
%   - For dRSAtypeToRun = 'PCR', autocorr-regression backend is selectable via
%     params.PCR.RegressStrategy:
%       * 'baseline_pcr_border' (legacy default)
%       * 'ridge_full_autocorr'
%       * 'ridge_tapered_autocorr'
%       * 'ar1_prewhite_ridge'
%     Additional tapered-ridge controls:
%       * params.PCR.AutoPenaltyStrength (>=0, stronger = more far-lag shrinkage)
%       * params.PCR.NormalizeAutoPenaltyPerRow (1/0, keep mean autocorr penalty stable per row)
%
% Existing-results decision system:
%   Configure existingResultsAction at the top of this script:
%     [] : interactive prompt (calls input with explicit 3 choices)
%      1 : reuse existing dataset and replot
%      2 : full rerun and overwrite outputs (default for batch safety)
%      3 : just error out if results already exist
%
% PE post-reappearance enforcement rule:
%   For occluded deviant trials, PE analyses always run post-reappearance.
%   - cutPostDev controls analysis streams only (models/targets/subsamples).
%   - cutPostDevPlot controls diagnostic path plots only.
%   - If cutPostDev is true: PE uses globally cut streams.
%   - If cutPostDev is false: PE applies an internal PE-only cut
%     to both observed and predicted streams before PE_signal is computed.
%   - The cut frame is derived from per-trial metadata:
%       reappearance_start_frame
%     with a fractional-onset fallback only when metadata is unavailable.
%
% Data flow summary:
%   1) Load one-dot center-relative condition trials from MovDot_SubXX.mat.
%   2) Build observed position/direction streams for each condition.
%   3) Load one-dot predicted occluded-deviant trials from MovDot_SubXX_predicted.mat.
%   4) Run standard occluded_nondeviant/occluded_deviant dRSA.
%   5) Build signal-level PE streams (observed - predicted), enforce PE
%      post-deviance windows, then run deviant PE dRSA for the three neural
%      targets above.
%   6) Save standard outputs + PE matrices + one-dot path plots + reproducibility
%      metadata with PE-specific post-deviance fields.
%
% Usage examples:
%   % Example 1: run from this folder.
%   cd('/Users/damiano/Documents/UniTn/Dynamo/Attention/DAD/simulations/scripts/one-dot');
%   PE_simulation_diff_1Dot_occlusion_v1;
%
%   % Example 2: run from anywhere with explicit participant + corr.
%   participantNumber = 70;
%   dRSAtypeToRun = 'corr';
%   run('/Users/damiano/Documents/UniTn/Dynamo/Attention/DAD/simulations/scripts/one-dot/PE_simulation_diff_1Dot_occlusion_v1.m');
%
%   % Example 3: run from anywhere with explicit participant + PCR.
%   participantNumber = 70;
%   dRSAtypeToRun = 'PCR';
%   run('/Users/damiano/Documents/UniTn/Dynamo/Attention/DAD/simulations/scripts/one-dot/PE_simulation_diff_1Dot_occlusion_v1.m');
%
%   % Example 4: non-interactive shell call with absolute MATLAB binary.
%   % arch -x86_64 /Applications/MATLAB_R2020a.app/bin/matlab -batch ...
%   % "cd('/Users/damiano/Documents/UniTn/Dynamo/Attention/DAD'); participantNumber=70; dRSAtypeToRun='corr'; run('simulations/scripts/one-dot/PE_simulation_diff_1Dot_occlusion_v1.m');"
%
% Inputs:
%   - experiment/input_files/MovDot_SubXX.mat
%   - experiment/input_files/MovDot_SubXX_predicted.mat (occluded deviant branch)
%
% Outputs:
%   - Standard one-dot outputs:
%       simulations/output/SubXX_oneDot_occlusion/<condition>/<dRSAtype>/{results,diagonal,matrices}
%       (for non-baseline PCR strategies, result filenames include a strategy tag,
%       e.g. *_pcrridgeFullAuto_* to prevent overwriting legacy PCR files)
%   - PE matrices:
%       simulations/output/SubXX_oneDot_occlusion/occluded_deviant/<dRSAtype>/matrices/PE/commCbar/*.png
%       simulations/output/SubXX_oneDot_occlusion/occluded_deviant/<dRSAtype>/matrices/PE/sepCbar/*.png
%   - PE paths figure:
%       simulations/output/SubXX_oneDot_occlusion/paths/*PE_paths*.png
%   - Results MAT fields:
%       dRSA_PE.neuralPE
%       dRSA_PE.neuralPredicted
%       dRSA_PE.neuralObserved
%
% Assumptions:
%   - Input uses one-dot xy columns [x y] from stimuli_generation_v18.m.
%   - Trial arrays are converted to center-relative coordinates in visual degrees.
%   - Trial lengths are uniform within each condition.
%   - dRSAtypeToRun must be one of: 'corr', 'PCR'.
%
% Preparatory steps (user-owned):
%   - smoothing / concatenation / run averaging / masking before simulation.

% Keep optional caller-provided overrides while resetting other workspace vars.
clearvars -except participantNumber inputConditions centerRelativeRectSize ...
    resampleSubsamples resampleIterations resampleSubsampleCount ...
    resampleWithReplacement cutPostDev cutPostDevPlot deviantOnset textScaleFactor ...
    dRSAtypeToRun existingResultsAction suppressDispText plotSampleRateHz params
close all

%% Resolve repo paths and add dependencies
% Data flow: script location -> repo root -> addpath for simulation helpers.
scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(fileparts(scriptDir)));
addpath(fullfile(repoRoot, 'simulations', 'functions'));
addpath(fullfile(repoRoot, 'simulations'));
addpath(fullfile(repoRoot, 'simulations', 'debug'));
addpath(repoRoot);

%% Debug gate (kept for parity with the base script)
% Data flow: debug flags -> optional downstream diagnostics.
if ~exist('params', 'var') || ~isstruct(params)
    params = struct();
end
if ~isfield(params, 'debug') || ~isstruct(params.debug)
    params.debug = struct();
end
params.debug.plotRDM = false; % gate to the rest of RDM debug params
params.debug.sampleIdx = 100;
params.debug.saveSnapshoot = true;

%% PCR strategy defaults (kept near top so output naming can use them)
% Data flow: caller-provided params.PCR overrides -> explicit defaults for reproducible runs.
if ~isfield(params, 'PCR') || ~isstruct(params.PCR)
    params.PCR = struct();
end
if ~isfield(params.PCR, 'RegressStrategy') || isempty(params.PCR.RegressStrategy)
    % Backward-compatible default that reproduces historical outputs.
    params.PCR.RegressStrategy = 'baseline_pcr_border';
end
if ~isfield(params.PCR, 'RidgeLambdaFactor') || isempty(params.PCR.RidgeLambdaFactor)
    if strcmpi(params.PCR.RegressStrategy, 'ar1_prewhite_ridge')
        params.PCR.RidgeLambdaFactor = 0.04;
    else
        params.PCR.RidgeLambdaFactor = 0.06;
    end
end
if ~isfield(params.PCR, 'TaperSigmaFactor') || isempty(params.PCR.TaperSigmaFactor)
    params.PCR.TaperSigmaFactor = 0.33;
end
if ~isfield(params.PCR, 'StandardizePredictors') || isempty(params.PCR.StandardizePredictors)
    params.PCR.StandardizePredictors = 1;
end
if ~isfield(params.PCR, 'AR1Clip') || isempty(params.PCR.AR1Clip)
    params.PCR.AR1Clip = 0.99;
end
if ~isfield(params.PCR, 'AutoPenaltyStrength') || isempty(params.PCR.AutoPenaltyStrength)
    % Strength for lag-dependent ridge penalties used by ridge_tapered_autocorr.
    params.PCR.AutoPenaltyStrength = 2;
end
if ~isfield(params.PCR, 'NormalizeAutoPenaltyPerRow') || ...
        isempty(params.PCR.NormalizeAutoPenaltyPerRow)
    % Row-wise normalization keeps total autocorr penalty comparable at edges.
    params.PCR.NormalizeAutoPenaltyPerRow = 1;
end

%% Participant configuration
% Data flow: participant number + condition list -> input filenames -> simulation data.
if ~exist('participantNumber', 'var') || isempty(participantNumber)
    participantNumber = 70;
end
if ~exist('inputConditions', 'var') || isempty(inputConditions)
    inputConditions = {'occluded_nondeviant', 'occluded_deviant'}; % conditions to run.
end
inputConditions = cellfun(@lower, inputConditions, 'UniformOutput', false);
if ~exist('centerRelativeRectSize', 'var')
    centerRelativeRectSize = []; % optional [width height] in degrees if Cfg.rectSize missing
end
if ~exist('resampleSubsamples', 'var') || isempty(resampleSubsamples)
    resampleSubsamples = false; % true to use per-iteration trial subsets for dRSA
end
if ~exist('resampleIterations', 'var') || isempty(resampleIterations)
    resampleIterations = 100; % number of resampled iterations (only if resampleSubsamples)
end
if ~exist('resampleSubsampleCount', 'var') || isempty(resampleSubsampleCount)
    resampleSubsampleCount = 100; % number of triggers per iteration (only if resampleSubsamples)
end
if ~exist('resampleWithReplacement', 'var') || isempty(resampleWithReplacement)
    resampleWithReplacement = false; % true = bootstrap-style resampling, false = unique subset per iteration
end
if ~exist('cutPostDev', 'var') || isempty(cutPostDev)
    cutPostDev = false; % true to keep only post-deviant samples in each trial
end
if ~exist('cutPostDevPlot', 'var') || isempty(cutPostDevPlot)
    cutPostDevPlot = false; % true to cut only path-plot diagnostics to post-deviant window
end
if ~exist('deviantOnset', 'var') || isempty(deviantOnset)
    % Fallback-only fraction used if reappearance metadata is unavailable.
    deviantOnset = 0.5;
end
if ~exist('textScaleFactor', 'var') || isempty(textScaleFactor)
    textScaleFactor = 2; % multiply axes/title/label text size across generated figures.
end
if ~exist('dRSAtypeToRun', 'var') || isempty(dRSAtypeToRun)
    dRSAtypeToRun = 'corr'; % set 'corr' or 'PCR' for the requested dRSA branch.
end
if ~exist('existingResultsAction', 'var')
    % [] = interactive prompt, 1 = reuse/replot, 2 = rerun/overwrite, 3 = error out.
    existingResultsAction = 2; % default non-interactive full rerun for batch execution.
end
if ~exist('suppressDispText', 'var') || isempty(suppressDispText)
    suppressDispText = 1; % 1 to suppress function-level status text, 0 to show.
end
if ~exist('plotSampleRateHz', 'var') || isempty(plotSampleRateHz)
    plotSampleRateHz = 120; % keep in sync with params.fs for seconds-based colorbars.
end

validConditions = {'occluded_nondeviant', 'occluded_deviant'};
if ~all(ismember(inputConditions, validConditions))
    error('inputConditions must be drawn from: %s', strjoin(validConditions, ', '));
end
validDRSATypes = {'corr', 'PCR'};
if ~any(strcmpi(dRSAtypeToRun, validDRSATypes))
    error('dRSAtypeToRun must be one of: %s', strjoin(validDRSATypes, ', '));
end
if ~(isempty(existingResultsAction) || ...
        (isnumeric(existingResultsAction) && isscalar(existingResultsAction) ...
        && ismember(existingResultsAction, [1, 2, 3])))
    error('existingResultsAction must be [], 1, 2, or 3.');
end
outputDir = fullfile(repoRoot, 'simulations', 'output');

%% Resolve raw input files and center-relative metadata source
% Data flow: participant number -> raw observed/predicted files -> one-dot loaders.
inputFile = fullfile(repoRoot, 'experiment', 'input_files', ...
    sprintf('MovDot_Sub%02d.mat', participantNumber));
predictedInputFile = fullfile(repoRoot, 'experiment', 'input_files', ...
    sprintf('MovDot_Sub%02d_predicted.mat', participantNumber));
if ~isfile(inputFile)
    error('Observed input file not found: %s', inputFile);
end

%% Load plotting config for center-distance diagnostics
% Data flow: input file -> Cfg.rectSize -> debug plot parameters.
cfgData = load(inputFile, 'Cfg');
rectSize = [];
if isfield(cfgData, 'Cfg') && isfield(cfgData.Cfg, 'rectSize')
    % Cfg.rectSize is Config.dotRectSize (visual degrees, origin at [0 0]).
    rectSize = cfgData.Cfg.rectSize;
elseif ~isempty(centerRelativeRectSize)
    rectSize = centerRelativeRectSize;
end

%% Plot one-dot paths for all conditions in a single figure
% Data flow: raw MovDot_SubXX.mat -> condition arrays -> shared-trial sample -> 1x3 path figure.
n = 20; % number of paths to plot per condition
allConditions = {'always_visible', 'occluded_nondeviant', 'occluded_deviant'};
pathsByCondition = struct();
metaByCondition = struct();
for iCond = 1:numel(allConditions)
    condName = allConditions{iCond};
    [condDot1Trials, condMeta] = local_load_one_dot_condition_trials( ...
        inputFile, condName, centerRelativeRectSize, false);
    if cutPostDevPlot
        % Plot-only gate: use metadata cut frame when available.
        plotCutFrame = local_resolve_cut_frame(condMeta, size(condDot1Trials, 3), deviantOnset);
        [condDot1Trials, ~] = local_cut_from_frame(condDot1Trials, plotCutFrame);
    end
    pathsByCondition.(condName).dot1 = condDot1Trials;
    metaByCondition.(condName) = condMeta;
end

[plotAlways, plotNondev, plotDev] = local_sample_same_trials_across_conditions( ...
    pathsByCondition.always_visible.dot1, ...
    metaByCondition.always_visible, ...
    pathsByCondition.occluded_nondeviant.dot1, ...
    metaByCondition.occluded_nondeviant, ...
    pathsByCondition.occluded_deviant.dot1, ...
    metaByCondition.occluded_deviant, ...
    n);

sharedAxisLimits = local_compute_shared_axis_limits({plotAlways, plotNondev, plotDev});
figAllPaths = local_plot_all_condition_paths_onedot( ...
    plotAlways, ...
    plotNondev, ...
    plotDev, ...
    sharedAxisLimits, ...
    plotSampleRateHz, ...
    sprintf('Dot paths one-dot (sub%02d, all conditions)', participantNumber), ...
    'on');

%% Run standard + PE dRSA per condition
% Data flow: condition list -> standard models -> optional deviant PE outputs.
for iCond = 1:numel(inputConditions)
    inputCondition = inputConditions{iCond};
    usePredictedModels = strcmp(inputCondition, 'occluded_deviant');
    reuseExistingResults = false;
    loadedResults = struct();
    existingActionUsed = [];
    cutFrame = [];
    conditionEventFrames = struct( ...
        'fullDisappearanceFrame', nan, ...
        'reappearanceStartFrame', nan, ...
        'reappearanceSource', 'missing');
    standardGuideTimes = struct( ...
        'fullDisappearanceSec', nan, ...
        'reappearanceStartSec', nan);
    peGuideTimes = struct( ...
        'fullDisappearanceSec', nan, ...
        'reappearanceStartSec', nan);
    dRSA_PE = struct(); % occluded_deviant-only; remains empty for occluded_nondeviant.
    peModelNames = {};
    peTargetLabels = {};
    figPEMatricesCommon = gobjects(0, 1);
    figPEMatricesSeparate = gobjects(0, 1);
    figPEPaths = gobjects(1, 1);
    pePathFile = '';
    peDot1 = [];
    dot1TrialsPredicted = [];
    predictedSimulationFile = '';
    observedInputFileUsed = '';
    observedInputField = '';
    observedInputColumns = [];
    predictedInputFileUsed = '';
    predictedInputField = '';
    predictedInputColumns = [];
    peDirectionDot1 = [];
    peCutFrame = [];
    peCutSource = 'notApplicable';
    pePostDevEnforced = usePredictedModels;
    peObservedPredictedSizeMatchBeforeCut = [];
    peObservedPredictedSizeMatchAfterCut = [];
    peTrialLenBeforeCut = [];
    peTrialLenAfterCut = [];
    peMaskSubsampling = [];
    peMaskTrigger = [];
    peSubsamples = [];
    peTriggerOptions = struct();

    %% Resolve condition labels and output paths
    % Data flow: condition -> labels -> deterministic output filenames.
    simulationInputFile = sprintf('MovDot_Sub%02d_%s.mat', participantNumber, inputCondition);
    subjectLabel = sprintf('sub%02d', participantNumber);
    conditionLabel = inputCondition;
    conditionSuffix = sprintf('(%s)', conditionLabel);
    dRSAtypeLabel = lower(dRSAtypeToRun);
    subjectOutputDir = fullfile(outputDir, sprintf('Sub%02d_oneDot_occlusion', participantNumber));
    if cutPostDev
        subjectOutputDir = fullfile(subjectOutputDir, 'postDev');
    end
    conditionOutputDir = fullfile(subjectOutputDir, conditionLabel);
    analysisOutputDir = fullfile(conditionOutputDir, dRSAtypeLabel);
    pathsOutputDir = fullfile(subjectOutputDir, 'paths');
    resultsOutputDir = fullfile(analysisOutputDir, 'results');
    diagonalOutputDir = fullfile(analysisOutputDir, 'diagonal');
    matricesOutputDir = fullfile(analysisOutputDir, 'matrices');
    peMatricesOutputDir = fullfile(matricesOutputDir, 'PE');
    peMatricesCommDir = '';
    peMatricesSepDir = '';
    % Data flow: model-group flag -> concrete matrix folders for export.
    if usePredictedModels
        baseMatricesDir = fullfile(matricesOutputDir, 'base');
        predictedMatricesDir = fullfile(matricesOutputDir, 'predicted');
        matricesBaseCommDir = fullfile(baseMatricesDir, 'commCbar');
        matricesBaseSepDir = fullfile(baseMatricesDir, 'sepCbar');
        matricesPredCommDir = fullfile(predictedMatricesDir, 'commCbar');
        matricesPredSepDir = fullfile(predictedMatricesDir, 'sepCbar');
        peMatricesCommDir = fullfile(peMatricesOutputDir, 'commCbar');
        peMatricesSepDir = fullfile(peMatricesOutputDir, 'sepCbar');
    else
        matricesBaseCommDir = fullfile(matricesOutputDir, 'commCbar');
        matricesBaseSepDir = fullfile(matricesOutputDir, 'sepCbar');
        matricesPredCommDir = '';
        matricesPredSepDir = '';
    end
    local_ensure_dir(resultsOutputDir);
    local_ensure_dir(diagonalOutputDir);
    local_ensure_dir(matricesBaseCommDir);
    local_ensure_dir(matricesBaseSepDir);
    if usePredictedModels
        local_ensure_dir(matricesPredCommDir);
        local_ensure_dir(matricesPredSepDir);
        local_ensure_dir(peMatricesCommDir);
        local_ensure_dir(peMatricesSepDir);
    end
    local_ensure_dir(pathsOutputDir);

    optionalTags = {'oneDot'};
    if ~usePredictedModels
        optionalTags{end + 1} = 'obsOnly';
    end
    if strcmpi(dRSAtypeToRun, 'PCR')
        % Add non-baseline strategy tag so alternative runs do not overwrite legacy PCR outputs.
        pcrStrategyTag = local_get_pcr_strategy_tag(params);
        if ~strcmp(pcrStrategyTag, 'baseline')
            optionalTags{end + 1} = ['pcr' pcrStrategyTag];
        end
    end
    if resampleSubsamples
        resampleMode = 'sub';
        if resampleWithReplacement
            resampleMode = 'boot';
        end
        optionalTags{end + 1} = sprintf('rs%d_i%d_%s', ...
            resampleSubsampleCount, resampleIterations, resampleMode);
    end
    runTagParts = [{subjectLabel, conditionLabel, lower(dRSAtypeToRun)}, optionalTags];
    resultsBase = strjoin([{'dRSA'}, runTagParts], '_');
    resultsBase = regexprep(resultsBase, '\s+', '');
    if usePredictedModels
        pePathFile = fullfile(pathsOutputDir, sprintf('%s_%s_PE_paths.png', resultsBase, conditionLabel));
    end
    resultsFile = fullfile(resultsOutputDir, [resultsBase '_results.mat']);
    legacyResultsFile = fullfile(subjectOutputDir, [resultsBase '_results.mat']);
    resultsFileToCheck = resultsFile;
    if ~isfile(resultsFile) && isfile(legacyResultsFile)
        % Backward-compat: allow reuse of flat outputs but write new plots to folders.
        resultsFileToCheck = legacyResultsFile;
    end

    %% Optional reuse of existing results
    % Data flow: existing results file -> parameter summary -> user-selected run mode.
    if isfile(resultsFileToCheck)
        existingMeta = load(resultsFileToCheck, 'repro', 'params');
        local_print_existing_match_summary( ...
            resultsFileToCheck, participantNumber, inputCondition, dRSAtypeToRun, ...
            resampleSubsamples, resampleIterations, ...
            resampleSubsampleCount, resampleWithReplacement, ...
            usePredictedModels, plotSampleRateHz, cutPostDev, cutPostDevPlot, deviantOnset, ...
            params.PCR.RegressStrategy, existingMeta);
        existingActionUsed = local_resolve_existing_results_action(existingResultsAction);
        if existingActionUsed == 3
            error(['Existing results found and existingResultsAction = 3. ' ...
                'Stopping without rerun: %s'], resultsFileToCheck);
        elseif existingActionUsed == 1
            loadedResults = load(resultsFileToCheck);
            requiredVars = {'dRSA_position', 'dRSA_direction', ...
                'dRSA_diagonal_position', 'dRSA_diagonal_direction', 'params'};
            if usePredictedModels
                % Deviant PE analyses require dRSA_PE with all three targets.
                requiredVars = [requiredVars, {'dRSA_PE'}];
            end
            missingVars = requiredVars(~isfield(loadedResults, requiredVars));
            if isempty(missingVars) && usePredictedModels
                peFieldNames = {'neuralPE', 'neuralPredicted', 'neuralObserved'};
                if ~isstruct(loadedResults.dRSA_PE) || ...
                        ~all(isfield(loadedResults.dRSA_PE, peFieldNames))
                    missingVars = [missingVars, {'dRSA_PE.(neuralPE/neuralPredicted/neuralObserved)'}];
                end
            end
            if isempty(missingVars)
                reuseExistingResults = true;
            else
                warning(['Existing file is missing required variables (%s). ' ...
                    'Falling back to full re-run.'], strjoin(missingVars, ', '));
            end
        else
            % existingActionUsed == 2 -> full rerun by design.
            fprintf('existingResultsAction=2: full rerun for %s.\n', conditionSuffix);
        end
    end

    if reuseExistingResults
        % Load saved matrices/metadata and skip expensive dRSA recomputation.
        dRSA_position = loadedResults.dRSA_position;
        dRSA_direction = loadedResults.dRSA_direction;
        dRSA_diagonal_position = loadedResults.dRSA_diagonal_position;
        dRSA_diagonal_direction = loadedResults.dRSA_diagonal_direction;
        params = loadedResults.params;
        if isfield(loadedResults, 'paramsDiagonal')
            paramsDiagonal = loadedResults.paramsDiagonal;
        else
            paramsDiagonal = params;
        end
        if isfield(loadedResults, 'repro') && isfield(loadedResults.repro, 'paramsCore')
            paramsCore = loadedResults.repro.paramsCore;
        else
            paramsCore = params;
        end
        if isfield(loadedResults, 'repro') && isfield(loadedResults.repro, 'modelNames')
            modelNames = loadedResults.repro.modelNames;
        else
            modelNames = local_default_model_names(size(dRSA_position, 3));
        end
        if usePredictedModels && isfield(loadedResults, 'dRSA_PE')
            dRSA_PE = loadedResults.dRSA_PE;
            peTargetLabels = fieldnames(dRSA_PE);
            if isfield(loadedResults, 'repro') && isfield(loadedResults.repro, 'peModelNames')
                peModelNames = loadedResults.repro.peModelNames;
            else
                peModelNames = {'PE position dot1', 'PE direction dot1'};
            end
            if isfield(loadedResults, 'repro') && isfield(loadedResults.repro, 'pePathFile')
                pePathFile = loadedResults.repro.pePathFile;
            end
            if isfield(loadedResults, 'repro') && isfield(loadedResults.repro, 'peDot1')
                peDot1 = loadedResults.repro.peDot1;
                figPEPaths = local_plot_pe_paths(peDot1, plotSampleRateHz, ...
                    sprintf('PE paths (sub%02d, %s)', participantNumber, inputCondition), 'on');
            end
        end
    else
        %% Load one-dot condition streams (center-relative visual degrees)
        % Data flow: raw .mat one-dot inputs -> condition split -> center-relative arrays.
        [dot1Trials, observedLoadMeta] = local_load_one_dot_condition_trials( ...
            inputFile, inputCondition, centerRelativeRectSize, false);
        observedInputFileUsed = observedLoadMeta.sourceFile;
        observedInputField = observedLoadMeta.xyField;
        observedInputColumns = observedLoadMeta.xyColumnCount;

        %% Load predicted one-dot occluded-deviant streams (deviant only)
        % Data flow: MovDot_SubXX_predicted.mat -> occluded_deviant condition -> one-dot arrays.
        dot1TrialsPredicted = [];
        predictedSimulationFile = '';
        predictedInputField = '';
        predictedInputColumns = [];
        conditionCutFrame = local_resolve_cut_frame(observedLoadMeta, size(dot1Trials, 3), deviantOnset);
        conditionEventFrames = local_resolve_plot_event_frames( ...
            observedLoadMeta, size(dot1Trials, 3), deviantOnset);
        if usePredictedModels
            if ~isfile(predictedInputFile)
                error('Predicted input file not found for deviant branch: %s', predictedInputFile);
            end
            [dot1TrialsPredicted, predictedLoadMeta] = local_load_one_dot_condition_trials( ...
                predictedInputFile, 'occluded_deviant', centerRelativeRectSize, true);
            predictedSimulationFile = predictedInputFile;
            predictedInputFileUsed = predictedLoadMeta.sourceFile;
            predictedInputField = predictedLoadMeta.xyField;
            predictedInputColumns = predictedLoadMeta.xyColumnCount;
            if ~isequal(size(dot1TrialsPredicted), size(dot1Trials))
                error(['Predicted occluded-deviant one-dot trials do not match observed size. ' ...
                    'Observed=%s Predicted=%s.'], mat2str(size(dot1Trials)), ...
                    mat2str(size(dot1TrialsPredicted)));
            end
        end

        %% Optional truncation from reappearance (or fallback deviant fraction)
        % Data flow: full trial paths + metadata cut frame -> truncated streams.
        if cutPostDev
            [dot1Trials, cutFrame] = local_cut_from_frame(dot1Trials, conditionCutFrame);
            if usePredictedModels
                [dot1TrialsPredicted, ~] = local_cut_from_frame(dot1TrialsPredicted, conditionCutFrame);
            end
        end
        if cutPostDev
            standardStartFrame = cutFrame;
        else
            standardStartFrame = 1;
        end
        standardGuideTimes = local_event_frames_to_seconds( ...
            conditionEventFrames, standardStartFrame, size(dot1Trials, 3), plotSampleRateHz);

        %% Prepare data, models, and trial-locked subsamples
        % Data flow: one-dot trial arrays -> position + direction models -> concatenated streams.
        plotConcat = 0; % suppress concatenation plots for batch runs
        dataPosition = dRSA_concatenate(dot1Trials, [], plotConcat, ...
            'suppressDispText', suppressDispText); % see documentation with help dRSA_concatenate

        % Standard one-dot models: observed position and observed direction.
        modelPositionDot1 = dataPosition;
        dot1Direction = local_positions_to_direction(dot1Trials);
        modelDirectionDot1 = dRSA_concatenate(dot1Direction, [], plotConcat, ...
            'suppressDispText', suppressDispText);
        dataDirection = modelDirectionDot1; % observed one-dot direction stream.

        modelPositionDot1Predicted = [];
        modelDirectionDot1Predicted = [];

        % PE branch placeholders.
        dataPositionPredicted = [];
        dataDirectionPredicted = [];
        dataPositionObservedPEWindow = [];
        dataDirectionObservedPEWindow = [];
        dataPositionPE = [];
        dataDirectionPE = [];
        modelPE = {};
        paramsPE = struct();

        if usePredictedModels
            predictedDot1Direction = local_positions_to_direction(dot1TrialsPredicted);
            modelPositionDot1Predicted = dRSA_concatenate(dot1TrialsPredicted, [], plotConcat, ...
                'suppressDispText', suppressDispText);
            modelDirectionDot1Predicted = dRSA_concatenate(predictedDot1Direction, [], plotConcat, ...
                'suppressDispText', suppressDispText);

            %% Enforce post-reappearance windows for PE branch (mandatory)
            % Data flow: observed+predicted streams -> metadata cut -> PE models/targets.
            peObservedDot1 = dot1Trials;
            pePredictedDot1 = dot1TrialsPredicted;
            peObservedPredictedSizeMatchBeforeCut = isequal(size(peObservedDot1), size(pePredictedDot1));
            if ~peObservedPredictedSizeMatchBeforeCut
                error('Observed and predicted one-dot streams must match before PE cut.');
            end
            peTrialLenBeforeCut = size(peObservedDot1, 3);

            if cutPostDev
                % Global cut already applied above; keep traceability for PE metadata.
                peCutSource = 'globalCutPostDev';
                peCutFrame = cutFrame;
            else
                % Apply mandatory PE-only cut from reappearance start when global cut is disabled.
                peCutFrame = conditionCutFrame;
                [peObservedDot1, ~] = local_cut_from_frame(peObservedDot1, peCutFrame);
                [pePredictedDot1, ~] = local_cut_from_frame(pePredictedDot1, peCutFrame);
                peCutSource = 'peBranchCut';
            end

            peObservedPredictedSizeMatchAfterCut = isequal(size(peObservedDot1), size(pePredictedDot1));
            if ~peObservedPredictedSizeMatchAfterCut
                error('Observed and predicted one-dot streams diverged after PE cut.');
            end
            peTrialLenAfterCut = size(peObservedDot1, 3);
            peGuideTimes = local_event_frames_to_seconds( ...
                conditionEventFrames, peCutFrame, peTrialLenAfterCut, plotSampleRateHz);

            %% Build signal-level PE models (observed - predicted)
            % Data flow: PE-cut observed/predicted streams -> one-dot PE position/direction models.
            peDot1 = peObservedDot1 - pePredictedDot1;
            modelPEPositionDot1 = dRSA_concatenate(peDot1, [], plotConcat, ...
                'suppressDispText', suppressDispText);

            peObservedDirectionDot1 = local_positions_to_direction(peObservedDot1);
            pePredictedDirectionDot1 = local_positions_to_direction(pePredictedDot1);
            peDirectionDot1 = peObservedDirectionDot1 - pePredictedDirectionDot1;
            modelPEDirectionDot1 = dRSA_concatenate(peDirectionDot1, [], plotConcat, ...
                'suppressDispText', suppressDispText);

            modelPE = {modelPEPositionDot1, modelPEDirectionDot1};
            peModelNames = {'PE position dot1', 'PE direction dot1'};

            %% Build PE neural targets from the same post-deviance window
            % Data flow: PE-cut observed/predicted streams -> observed/predicted/PE targets.
            dataPositionObservedPEWindow = dRSA_concatenate(peObservedDot1, [], plotConcat, ...
                'suppressDispText', suppressDispText);
            dataDirectionObservedPEWindow = dRSA_concatenate(peObservedDirectionDot1, [], plotConcat, ...
                'suppressDispText', suppressDispText);
            dataPositionPredicted = dRSA_concatenate(pePredictedDot1, [], plotConcat, ...
                'suppressDispText', suppressDispText);
            dataDirectionPredicted = dRSA_concatenate(pePredictedDirectionDot1, [], plotConcat, ...
                'suppressDispText', suppressDispText);
            dataPositionPE = dataPositionObservedPEWindow - dataPositionPredicted;
            dataDirectionPE = dataDirectionObservedPEWindow - dataDirectionPredicted;

            % Additional PE paths figure (deviant only), saved under subject-level paths.
            figPEPaths = local_plot_pe_paths(peDot1, plotSampleRateHz, ...
                sprintf('PE paths (sub%02d, %s)', participantNumber, inputCondition), 'on');
        end

        %% Build trial-locked subsamples
        % Data flow: trial length -> trigger mask -> subsamples tensor for dRSA.
        trialLen = size(dot1Trials, 3);
        totalTime = size(dataPosition, 2);
        [maskSubsampling, maskTrigger, opt, subsamples] = local_build_trial_subsamples(trialLen, totalTime);

        %% Optional subsample resampling (memory control)
        % Data flow: full trial subsamples -> (optional) resampled subsets -> iteration tensor.
        if resampleSubsamples
            subsamples = local_resample_subsamples( ...
                subsamples, resampleSubsampleCount, resampleIterations, resampleWithReplacement);
        end

        %% Build PE-specific subsamples (deviant only)
        % Data flow: PE post-deviance trial length -> PE-specific trigger tensor.
        if usePredictedModels
            peTotalTime = size(dataPositionObservedPEWindow, 2);
            [peMaskSubsampling, peMaskTrigger, peTriggerOptions, peSubsamples] = ...
                local_build_trial_subsamples(peTrialLenAfterCut, peTotalTime);
            if resampleSubsamples
                peSubsamples = local_resample_subsamples( ...
                    peSubsamples, resampleSubsampleCount, resampleIterations, resampleWithReplacement);
            end
        end

        %% Configure dRSA models and parameters
        % Data flow: one-dot position/direction models -> dRSA parameters -> core calls.
        Y = dataPosition; % observed one-dot position stream
        model = {modelPositionDot1, modelDirectionDot1};
        modelNames = {'position dot1', 'direction dot1'};
        if usePredictedModels
            model = {modelPositionDot1, modelDirectionDot1, ...
                modelPositionDot1Predicted, modelDirectionDot1Predicted};
            modelNames = {'position dot1', 'direction dot1', ...
                'predicted position dot1', 'predicted direction dot1'};
        end

        params.modelNames = modelNames;
        % Standard dRSA params shared by corr and PCR branches.
        params.nIter = size(subsamples, 3);  % how many iterations?
        params.fs = plotSampleRateHz; % framerate or how many samples fit into 1 second
        % Use an integer sample window for averaging to avoid non-integer sizes.
        avgHalfWindowSamples = floor((trialLen - 1) / 2);
        params.AverageTime = avgHalfWindowSamples / params.fs; % in s
        params.modelToTest = 1:numel(model); % array of models to test
        params.Var = 0.1; % how much variance?
        params.modelDistMeasure = {'euclidean', 'cosine'};
        if usePredictedModels
            params.modelDistMeasure = [params.modelDistMeasure, {'euclidean', 'cosine'}];
        end
        params.neuralDistMeasure = params.modelDistMeasure{1}; % pdist expects a string/char or function handle.

        params.dRSAtype = dRSAtypeToRun; % dRSA branch selected in top-level config.
        % Keep PCR fields populated while preserving caller overrides.
        if ~isfield(params.PCR, 'AdditionalPCA') || isempty(params.PCR.AdditionalPCA)
            params.PCR.AdditionalPCA = 1;
        end
        if ~isfield(params.PCR, 'RegressAutocor') || isempty(params.PCR.RegressAutocor)
            params.PCR.RegressAutocor = 1;
        end
        if ~isfield(params.PCR, 'RessModel') || isempty(params.PCR.RessModel)
            params.PCR.RessModel = 1;
        end

        params.modeltoRegressout = cell(1, numel(model));
        for iModel = 1:numel(model)
            params.modeltoRegressout{iModel} = setdiff(1:numel(model), iModel);
        end

        % Autocorrelation border is only required by the legacy baseline PCR backend.
        Autocorrborder = []; % empty signals "no border" to downstream code paths.
        if ~strcmp(params.dRSAtype, 'corr')
            if strcmp(params.PCR.RegressStrategy, 'baseline_pcr_border')
                Autocorrborder = dRSA_border(model, subsamples, params, ...
                    'suppressDispText', suppressDispText, 'plotAutocorr', 'on');
            else
                % Keep explicit NaN borders in metadata for non-border strategies.
                Autocorrborder = nan(numel(model), 1);
            end
        end

        %% Configure PE dRSA parameters (deviant only)
        % Data flow: shared params -> PE-specific model list + fixed model metrics.
        if usePredictedModels
            paramsPE = params;
            paramsPE.nIter = size(peSubsamples, 3);
            avgHalfWindowSamplesPE = floor((peTrialLenAfterCut - 1) / 2);
            paramsPE.AverageTime = avgHalfWindowSamplesPE / paramsPE.fs;
            paramsPE.modelNames = peModelNames;
            paramsPE.modelToTest = 1:numel(modelPE);
            paramsPE.modelDistMeasure = {'euclidean', 'cosine'};
            paramsPE.modeltoRegressout = cell(1, numel(modelPE));
            for iModel = 1:numel(modelPE)
                paramsPE.modeltoRegressout{iModel} = setdiff(1:numel(modelPE), iModel);
            end
        end
    end

    %% Run dRSA for position data
    % Data flow: position data -> distance metric aligned to position model -> dRSA.
    params.neuralDistMeasure = params.modelDistMeasure{1};
    dRSA_Iter = [];
    for iIter = 1:params.nIter
        CurrSubsamples = subsamples(:, :, iIter); % subsamples is nSubsamples*subSampleDuration*iterations
        dRSAma = dRSA_coreFunction(Y, model, params, ...
            'CurrSubsamples', CurrSubsamples, 'Autocorrborder', Autocorrborder);
        dRSA_Iter(iIter, :, :, :) = dRSAma;
    end
    dRSA_position = mean(dRSA_Iter, 1);
    dRSA_position = reshape(dRSA_position, size(dRSA_position, 2), size(dRSA_position, 3), size(dRSA_position, 4));

    %% Run dRSA for direction data
    % Data flow: direction data -> distance metric aligned to direction model -> dRSA.
    params.neuralDistMeasure = params.modelDistMeasure{2};
    Y = dataDirection; % direction data from dot 1
    dRSA_Iter = [];
    for iIter = 1:params.nIter
        CurrSubsamples = subsamples(:, :, iIter); % subsamples is nSubsamples*subSampleDuration*iterations
        dRSAma = dRSA_coreFunction(Y, model, params, ...
            'CurrSubsamples', CurrSubsamples, 'Autocorrborder', Autocorrborder);
        dRSA_Iter(iIter, :, :, :) = dRSAma;
    end
    dRSA_direction = mean(dRSA_Iter, 1);
    dRSA_direction = reshape(dRSA_direction, size(dRSA_direction, 2), size(dRSA_direction, 3), size(dRSA_direction, 4));

    %% Run deviant-only PE dRSA using three neural targets
    % Data flow: (PE neural target stream, PE models, PE subsamples) -> dRSA PE matrices.
    if usePredictedModels
        peTargetLabels = {'neuralPE', 'neuralPredicted', 'neuralObserved'};
        peTargetPositionData = {dataPositionPE, dataPositionPredicted, dataPositionObservedPEWindow};
        peTargetDirectionData = {dataDirectionPE, dataDirectionPredicted, dataDirectionObservedPEWindow};
        for iTarget = 1:numel(peTargetLabels)
            currTargetLabel = peTargetLabels{iTarget};

            % Position row for current PE neural target.
            paramsPE.neuralDistMeasure = paramsPE.modelDistMeasure{1};
            Y = peTargetPositionData{iTarget};
            dRSA_Iter = [];
            for iIter = 1:paramsPE.nIter
                CurrSubsamples = peSubsamples(:, :, iIter);
                dRSAma = dRSA_coreFunction(Y, modelPE, paramsPE, ...
                    'CurrSubsamples', CurrSubsamples, 'Autocorrborder', Autocorrborder);
                dRSA_Iter(iIter, :, :, :) = dRSAma;
            end
            dRSA_position_pe = mean(dRSA_Iter, 1);
            dRSA_position_pe = reshape(dRSA_position_pe, ...
                size(dRSA_position_pe, 2), size(dRSA_position_pe, 3), size(dRSA_position_pe, 4));

            % Direction row for current PE neural target.
            paramsPE.neuralDistMeasure = paramsPE.modelDistMeasure{2};
            Y = peTargetDirectionData{iTarget};
            dRSA_Iter = [];
            for iIter = 1:paramsPE.nIter
                CurrSubsamples = peSubsamples(:, :, iIter);
                dRSAma = dRSA_coreFunction(Y, modelPE, paramsPE, ...
                    'CurrSubsamples', CurrSubsamples, 'Autocorrborder', Autocorrborder);
                dRSA_Iter(iIter, :, :, :) = dRSAma;
            end
            dRSA_direction_pe = mean(dRSA_Iter, 1);
            dRSA_direction_pe = reshape(dRSA_direction_pe, ...
                size(dRSA_direction_pe, 2), size(dRSA_direction_pe, 3), size(dRSA_direction_pe, 4));

            % Save current neural-target matrices into the PE output struct.
            dRSA_PE.(currTargetLabel) = struct( ...
                'position', dRSA_position_pe, ...
                'direction', dRSA_direction_pe, ...
                'modelNames', {peModelNames}, ...
                'rowNames', {{'Data: position PE target', 'Data: direction PE target'}});
        end
    end

    % Preserve parameters used for dRSA before reusing them for diagonal averaging.
    paramsCore = params;

    %% Plot dRSA matrices (position vs direction data)
    % Data flow: dRSA per data type (time x time x model) -> grid of heatmaps.
    % Axes share 5 ticks and replace the midpoint tick label with 'M'.
    nModels = size(dRSA_position, 3);
    nTime = size(dRSA_position, 1);
    timeSeconds = (0:nTime-1) / paramsCore.fs;
    dRSAAll = {dRSA_position, dRSA_direction};
    rowNames = {'Data: position dot1', 'Data: direction dot1'};
    baseModelIdx = 1:2;
    predictedModelIdx = 3:nModels;
    hasPredictedModels = nModels > numel(baseModelIdx);
    figLabels = {};
    if hasPredictedModels
        figLabels = {'base', 'predicted'};
    else
        figLabels = {'base'};
    end
    cbarLimits = [0 1];
    % Always create both matrix variants on screen for direct comparison.
    figMatricesCommon = local_plot_dRSA_matrices( ...
        dRSAAll, modelNames, rowNames, timeSeconds, figLabels, ...
        baseModelIdx, predictedModelIdx, true, cbarLimits, 'on', standardGuideTimes);
    figMatricesSeparate = local_plot_dRSA_matrices( ...
        dRSAAll, modelNames, rowNames, timeSeconds, figLabels, ...
        baseModelIdx, predictedModelIdx, false, cbarLimits, 'on', standardGuideTimes);

    %% Plot deviant-only PE matrices (three neural targets, each 2x2)
    % Data flow: PE dRSA struct -> per-target 2x2 matrix figures -> handle arrays.
    if usePredictedModels
        if isempty(peModelNames)
            peModelNames = {'PE position dot1', 'PE direction dot1'};
        end
        % PE matrices can use a shorter post-deviance window than standard matrices.
        peNTime = size(dRSA_PE.neuralPE.position, 1);
        peTimeSeconds = (0:peNTime-1) / paramsCore.fs;
        figPEMatricesCommon = local_plot_pe_matrices( ...
            dRSA_PE, peModelNames, peTimeSeconds, true, cbarLimits, 'on', peGuideTimes);
        figPEMatricesSeparate = local_plot_pe_matrices( ...
            dRSA_PE, peModelNames, peTimeSeconds, false, cbarLimits, 'on', peGuideTimes);
    end

    %% Plot diagonal
    % Data flow: dRSA matrices -> diagonal averages -> summary lines.
    paramsDiagonal = paramsCore;
    paramsDiagonal.AverageTime = 2; % in s, how much should be left and right of the zerolag middle?
    dRSA_diagonal_position = dRSA_average(dRSA_position, paramsDiagonal);
    dRSA_diagonal_direction = dRSA_average(dRSA_direction, paramsDiagonal);

    figLag = figure('Name', 'dRSA diagonal', 'NumberTitle', 'off');
    hold on;
    plot(dRSA_diagonal_position(1, :), 'LineWidth', 1.5);
    plot(dRSA_diagonal_direction(2, :), 'LineWidth', 1.5);
    hold off;
    xlabel('Time (samples)');
    ylabel('dRSA (diagonal)');
    legend(rowNames, 'Location', 'best');

    %% Save matrices, plots, and reproducibility metadata (300 dpi)
    % Data flow: dRSA outputs + run metadata -> descriptive filenames -> .mat/.png outputs.
    if ~reuseExistingResults
        repro = struct();
        repro.timestamp = datestr(now, 'yyyymmddTHHMMSS');
        repro.scriptPath = mfilename('fullpath');
        repro.repoRoot = repoRoot;
        repro.matlabVersion = version;
        repro.participantNumber = participantNumber;
        repro.subjectLabel = subjectLabel;
        repro.inputCondition = inputCondition;
        repro.conditionLabel = conditionLabel;
        repro.simulationInputFile = simulationInputFile;
        repro.rawInputFile = inputFile;
        repro.oneDotOnly = true;
        repro.existingResultsActionConfig = existingResultsAction;
        repro.existingResultsActionUsed = existingActionUsed;
        repro.resampleSubsamples = resampleSubsamples;
        repro.resampleIterations = resampleIterations;
        repro.resampleSubsampleCount = resampleSubsampleCount;
        repro.resampleWithReplacement = resampleWithReplacement;
        repro.cutPostDev = cutPostDev;
        repro.cutPostDevPlot = cutPostDevPlot;
        repro.deviantOnset = deviantOnset;
        repro.cutFrame = cutFrame;
        repro.trialLen = trialLen;
        repro.totalTime = totalTime;
        repro.nTrials = size(dot1Trials, 1);
        repro.nModels = nModels;
        repro.modelNames = modelNames;
        repro.paramsCore = paramsCore;
        repro.paramsDiagonal = paramsDiagonal;
        repro.pcrRegressStrategy = paramsCore.PCR.RegressStrategy;
        repro.pcrRidgeLambdaFactor = paramsCore.PCR.RidgeLambdaFactor;
        repro.pcrTaperSigmaFactor = paramsCore.PCR.TaperSigmaFactor;
        repro.pcrStandardizePredictors = paramsCore.PCR.StandardizePredictors;
        repro.pcrAR1Clip = paramsCore.PCR.AR1Clip;
        repro.pcrAutoPenaltyStrength = paramsCore.PCR.AutoPenaltyStrength;
        repro.pcrNormalizeAutoPenaltyPerRow = paramsCore.PCR.NormalizeAutoPenaltyPerRow;
        repro.triggerOptions = opt;
        repro.maskSubsampling = maskSubsampling;
        repro.maskTrigger = maskTrigger;
        repro.subsamples = subsamples;
        repro.rectSize = rectSize;
        repro.dot1Trials = dot1Trials;
        repro.dot1TrialsPredicted = dot1TrialsPredicted;
        repro.dataPosition = dataPosition;
        repro.dataDirection = dataDirection;
        repro.models = model;
        repro.autocorrBorder = Autocorrborder;
        repro.observedInputFileUsed = observedInputFileUsed;
        repro.observedInputField = observedInputField;
        repro.observedInputColumns = observedInputColumns;
        repro.predictedInputFileUsed = predictedInputFileUsed;
        repro.predictedInputField = predictedInputField;
        repro.predictedInputColumns = predictedInputColumns;
        repro.predictedSimulationFile = predictedSimulationFile;
        repro.peModelNames = peModelNames;
        repro.peTargetLabels = peTargetLabels;
        repro.peDot1 = peDot1;
        repro.peDirectionDot1 = peDirectionDot1;
        repro.pePathFile = pePathFile;
        repro.pePostDevEnforced = pePostDevEnforced;
        repro.peCutSource = peCutSource;
        repro.peCutFrame = peCutFrame;
        repro.occlusionEventFrames = conditionEventFrames;
        repro.standardGuideTimesSec = standardGuideTimes;
        repro.peGuideTimesSec = peGuideTimes;
        repro.peTrialLenBeforeCut = peTrialLenBeforeCut;
        repro.peTrialLenAfterCut = peTrialLenAfterCut;
        repro.peObservedPredictedSizeMatchBeforeCut = peObservedPredictedSizeMatchBeforeCut;
        repro.peObservedPredictedSizeMatchAfterCut = peObservedPredictedSizeMatchAfterCut;
        repro.peMaskSubsampling = peMaskSubsampling;
        repro.peMaskTrigger = peMaskTrigger;
        repro.peSubsamples = peSubsamples;
        repro.peTriggerOptions = peTriggerOptions;

        save(resultsFile, ...
            'dRSA_position', 'dRSA_direction', ...
            'dRSA_diagonal_position', 'dRSA_diagonal_direction', ...
            'dRSA_PE', 'params', 'paramsDiagonal', 'repro');
    else
        fprintf('Using existing dataset for %s; only re-plotting figures.\n', conditionSuffix);
    end

    % Maximize figures before export so matrices occupy more pixels in saved PNGs.
    for iFigPrep = 1:numel(figMatricesCommon)
        local_scale_figure_text(figMatricesCommon(iFigPrep), textScaleFactor);
        local_prepare_figure_for_export(figMatricesCommon(iFigPrep));
    end
    for iFigPrep = 1:numel(figMatricesSeparate)
        local_scale_figure_text(figMatricesSeparate(iFigPrep), textScaleFactor);
        local_prepare_figure_for_export(figMatricesSeparate(iFigPrep));
    end
    for iFigPrep = 1:numel(figPEMatricesCommon)
        local_scale_figure_text(figPEMatricesCommon(iFigPrep), textScaleFactor);
        local_prepare_figure_for_export(figPEMatricesCommon(iFigPrep));
    end
    for iFigPrep = 1:numel(figPEMatricesSeparate)
        local_scale_figure_text(figPEMatricesSeparate(iFigPrep), textScaleFactor);
        local_prepare_figure_for_export(figPEMatricesSeparate(iFigPrep));
    end
    % Keep lag plots at their native size/text for readability consistency.
    if iCond == 1
        local_scale_figure_text(figAllPaths, textScaleFactor);
        local_prepare_figure_for_export(figAllPaths);
    end
    if usePredictedModels && isgraphics(figPEPaths, 'figure')
        local_scale_figure_text(figPEPaths, textScaleFactor);
        local_prepare_figure_for_export(figPEPaths);
    end

    % Save both colorbar variants (guard against invalid figure handles).
    if numel(figLabels) == 1
        local_safe_print(figMatricesCommon(1), ...
            fullfile(matricesBaseCommDir, [resultsBase '_matrices_commCbar.png']));
        local_safe_print(figMatricesSeparate(1), ...
            fullfile(matricesBaseSepDir, [resultsBase '_matrices_sepCbar.png']));
    else
        local_safe_print(figMatricesCommon(1), ...
            fullfile(matricesBaseCommDir, [resultsBase '_matrices_base_commCbar.png']));
        local_safe_print(figMatricesCommon(2), ...
            fullfile(matricesPredCommDir, [resultsBase '_matrices_predicted_commCbar.png']));
        local_safe_print(figMatricesSeparate(1), ...
            fullfile(matricesBaseSepDir, [resultsBase '_matrices_base_sepCbar.png']));
        local_safe_print(figMatricesSeparate(2), ...
            fullfile(matricesPredSepDir, [resultsBase '_matrices_predicted_sepCbar.png']));
    end
    if usePredictedModels
        peTargetOrder = {'neuralPE', 'neuralPredicted', 'neuralObserved'};
        for iTarget = 1:numel(peTargetOrder)
            targetLabel = peTargetOrder{iTarget};
            local_safe_print(figPEMatricesCommon(iTarget), ...
                fullfile(peMatricesCommDir, sprintf('%s_PE_%s_commCbar.png', resultsBase, targetLabel)));
            local_safe_print(figPEMatricesSeparate(iTarget), ...
                fullfile(peMatricesSepDir, sprintf('%s_PE_%s_sepCbar.png', resultsBase, targetLabel)));
        end
        pePathFile = fullfile(pathsOutputDir, sprintf('%s_%s_PE_paths.png', resultsBase, conditionLabel));
        local_safe_print(figPEPaths, pePathFile);
    end
    local_safe_print(figLag, fullfile(diagonalOutputDir, [resultsBase '_diagonal.png']));
    if iCond == 1
        pathsBase = strjoin({'paths', subjectLabel, 'allConditions'}, '_');
        pathsBase = regexprep(pathsBase, '\s+', '');
        local_safe_print(figAllPaths, fullfile(pathsOutputDir, [pathsBase '_all_conditions.png']));
    end
end

%% Local helpers
function local_ensure_dir(dirPath)
% LOCAL_ENSURE_DIR Create the directory if it is missing (including parents).
if isempty(dirPath)
    return;
end
if ~exist(dirPath, 'dir')
    mkdir(dirPath);
end
end

function local_safe_print(figHandle, outPath)
% LOCAL_SAFE_PRINT Export a figure with compact layout if the handle is valid.
%
% Inputs:
%   figHandle : figure handle to export.
%   outPath   : absolute output path for the PNG file.
%
% Data flow:
%   figure handle -> tiledlayout/figure export path -> 300 dpi PNG on disk.
%
% Notes:
%   - Uses exportgraphics to preserve tiledlayout bounds and reduce extra
%     whitespace compared with figure-level print.
%   - Falls back to print for environments where exportgraphics fails.
if isempty(figHandle) || ~isgraphics(figHandle, 'figure')
    warning('Skipping print; invalid figure handle for %s', outPath);
    return;
end
[outDir, ~, ~] = fileparts(outPath);
local_ensure_dir(outDir);

layoutHandle = findobj(figHandle, 'Type', 'tiledlayout', '-depth', 1);
try
    if ~isempty(layoutHandle)
        exportgraphics(layoutHandle(1), outPath, 'Resolution', 300, ...
            'BackgroundColor', 'white');
    else
        exportgraphics(figHandle, outPath, 'Resolution', 300, ...
            'BackgroundColor', 'white');
    end
catch
    print(figHandle, outPath, '-dpng', '-r300');
end
end

function direction = local_positions_to_direction(paths)
% LOCAL_POSITIONS_TO_DIRECTION Convert x/y path samples to unit-vector directions.
%
% Inputs:
%   paths : trials x 2 x time center-relative positions.
%
% Outputs:
%   direction : trials x 2 x time where columns are [cos(theta), sin(theta)].
%
% Data flow:
%   positions -> frame-to-frame displacement -> angle -> unit-vector direction.
if isempty(paths)
    direction = paths;
    return;
end
if size(paths, 3) < 2
    % Edge case: one-sample trials have no displacement; keep neutral vectors.
    direction = zeros(size(paths));
    return;
end
dx = diff(paths(:, 1, :), 1, 3);
dy = diff(paths(:, 2, :), 1, 3);
dx = cat(3, dx(:, :, 1), dx); % keep time length aligned to original paths.
dy = cat(3, dy(:, :, 1), dy);
angle = atan2(dy, dx);
direction = cat(2, cos(angle), sin(angle));
end

function [maskSubsampling, maskTrigger, opt, subsamples] = ...
        local_build_trial_subsamples(trialLen, totalTime)
% LOCAL_BUILD_TRIAL_SUBSAMPLES Build trial-locked subsamples for dRSA.
%
% Inputs:
%   trialLen  : number of samples per trial window.
%   totalTime : total concatenated sample length.
%
% Outputs:
%   maskSubsampling : logical mask of eligible time points.
%   maskTrigger     : logical trigger vector with one trigger per trial start.
%   opt             : dRSA_triggered_subsampling options used.
%   subsamples      : nSubSamples x subSampleDuration x nIter trigger windows.
if mod(totalTime, trialLen) ~= 0
    error('Total time (%d) is not a multiple of trial length (%d).', totalTime, trialLen);
end
maskSubsampling = true(1, totalTime);
trialStarts = 1:trialLen:totalTime;
maskTrigger = false(1, totalTime);
maskTrigger(trialStarts) = true;

opt.PreTrigger = 0;
opt.PostTrigger = trialLen - 1;
opt.spacing = 0;
opt.nSubSamples = numel(trialStarts);
opt.nIter = 1;
opt.checkRepetition = 0;

subsamples = dRSA_triggered_subsampling(maskSubsampling, maskTrigger, opt);
end

function subsamples = local_resample_subsamples( ...
        subsamples, resampleSubsampleCount, resampleIterations, resampleWithReplacement)
% LOCAL_RESAMPLE_SUBSAMPLES Optional resampling wrapper for subsample tensors.
%
% Inputs:
%   subsamples              : base subsample tensor from triggered sampling.
%   resampleSubsampleCount  : number of subsamples per iteration.
%   resampleIterations      : number of iterations.
%   resampleWithReplacement : true for bootstrap-style resampling.
%
% Outputs:
%   subsamples : resampled subsample tensor (count x duration x iterations).
baseSubsamples = subsamples(:, :, 1);
baseCount = size(baseSubsamples, 1);
if resampleSubsampleCount > baseCount
    error('resampleSubsampleCount (%d) exceeds available subsamples (%d).', ...
        resampleSubsampleCount, baseCount);
end
if resampleWithReplacement
    resamplePercent = 100 * (resampleSubsampleCount / baseCount);
    subsamples = dRSA_resample_subsamples(baseSubsamples, resampleIterations, resamplePercent);
else
    subsamples = zeros(resampleSubsampleCount, size(baseSubsamples, 2), resampleIterations);
    for iIter = 1:resampleIterations
        drawIdx = randperm(baseCount, resampleSubsampleCount);
        subsamples(:, :, iIter) = baseSubsamples(drawIdx, :);
    end
end
end

function figMatrices = local_plot_dRSA_matrices( ...
        dRSAAll, modelNames, rowNames, timeSeconds, figLabels, ...
        baseModelIdx, predictedModelIdx, useCommonCbarLimits, cbarLimits, figVisibility, guideTimes)
% LOCAL_PLOT_DRSA_MATRICES Render dRSA matrix figures with standardized ticks.
%
% Usage example:
%   figH = local_plot_dRSA_matrices(dRSAAll, modelNames, rowNames, timeSeconds, ...
%       {'base'}, 1:2, [], true, [0 1], 'on');
%
% Inputs:
%   dRSAAll             : 1x2 cell {dRSA_position, dRSA_direction}.
%   modelNames          : 1xnModels cell of model labels.
%   rowNames            : 1x2 cell of row labels.
%   timeSeconds         : 1xnTime time axis in seconds.
%   figLabels           : figure groups ('base', 'predicted').
%   baseModelIdx        : indices of base models in the third dRSA dimension.
%   predictedModelIdx     : indices of predicted models in the third dRSA dimension.
%   useCommonCbarLimits : true for shared row colorbars + fixed limits.
%   cbarLimits          : [min max] colorbar limits used when sharing.
%   figVisibility       : 'on' to show figures, 'off' to keep hidden.
%   guideTimes          : struct with optional guide times (seconds):
%                         .fullDisappearanceSec, .reappearanceStartSec.
%
% Output:
%   figMatrices         : array of figure handles, one per entry in figLabels.
%
% Data flow:
%   dRSA tensors -> per-group tiled figures -> shared five-tick axes with
%   midpoint tick labeled 'M' -> optional shared or per-subplot colorbars.

figMatrices = gobjects(numel(figLabels), 1);
[timeTicks, timeTickLabels] = local_build_midpoint_ticks(timeSeconds);

for iFig = 1:numel(figLabels)
    if strcmp(figLabels{iFig}, 'base')
        modelIdx = baseModelIdx;
    else
        modelIdx = predictedModelIdx;
    end

    figMatrices(iFig) = figure( ...
        'Name', sprintf('dRSA matrices (%s)', figLabels{iFig}), ...
        'NumberTitle', 'off', ...
        'Visible', figVisibility);
    tiledlayout(2, numel(modelIdx), 'Padding', 'compact', 'TileSpacing', 'compact');
    rowAxes = gobjects(numel(dRSAAll), numel(modelIdx));

    for iRow = 1:numel(dRSAAll)
        for iModel = 1:numel(modelIdx)
            tileIdx = (iRow - 1) * numel(modelIdx) + iModel;
            modelCol = modelIdx(iModel);
            nexttile(tileIdx);
            imagesc(timeSeconds, timeSeconds, dRSAAll{iRow}(:, :, modelCol));
            set(gca, 'YDir', 'normal');
            axis image;
            if ~useCommonCbarLimits
                colorbar;
            end
            title(sprintf('dRSA %s', modelNames{modelCol}));
            % dRSA uses corr(modelRDM, neuralRDM): x = neural/data time, y = model time.
            xlabel(sprintf('Time in %s (s)', rowNames{iRow}));
            ylabel(sprintf('Time in %s (s)', modelNames{modelCol}));
            xticks(timeTicks);
            yticks(timeTicks);
            xticklabels(timeTickLabels);
            yticklabels(timeTickLabels);
            hold on;
            plot(timeSeconds, timeSeconds, 'w-', 'LineWidth', 1);
            local_overlay_time_guides(gca, guideTimes);
            hold off;
            if useCommonCbarLimits
                caxis(cbarLimits);
            end
            rowAxes(iRow, iModel) = gca;
        end
    end

    if useCommonCbarLimits
        for iRow = 1:numel(dRSAAll)
            cbarHandle = colorbar(rowAxes(iRow, end), 'Location', 'eastoutside');
            cbarHandle.Limits = cbarLimits;
        end
    end
end
end

function figPEMatrices = local_plot_pe_matrices( ...
        dRSA_PE, peModelNames, timeSeconds, useCommonCbarLimits, cbarLimits, figVisibility, guideTimes)
% LOCAL_PLOT_PE_MATRICES Plot deviant PE dRSA matrices for each PE neural target.
%
% Purpose:
%   Render one figure per PE neural target. Each figure always uses a
%   2xN layout: row 1 = position neural stream, row 2 = direction neural
%   stream, and columns = the one-dot PE model set.
%
% Inputs:
%   dRSA_PE             : struct with fields neuralPE/neuralPredicted/neuralObserved.
%   peModelNames        : 1xN model labels for PE model columns.
%   timeSeconds         : 1xnTime time axis in seconds.
%   useCommonCbarLimits : true for shared [min max] per-row colorbars.
%   cbarLimits          : [min max] limits when useCommonCbarLimits=true.
%   figVisibility       : 'on' or 'off'.
%   guideTimes          : struct with optional guide times (seconds):
%                         .fullDisappearanceSec, .reappearanceStartSec.
%
% Output:
%   figPEMatrices       : 3x1 array of figure handles in fixed target order.
%
% Data flow:
%   PE dRSA struct -> target-specific matrix pairs -> standardized 2xN figures.

targetOrder = {'neuralPE', 'neuralPredicted', 'neuralObserved'};
rowNames = {'PE neural target (position)', 'PE neural target (direction)'};
figPEMatrices = gobjects(numel(targetOrder), 1);

[timeTicks, timeTickLabels] = local_build_midpoint_ticks(timeSeconds);

for iTarget = 1:numel(targetOrder)
    targetLabel = targetOrder{iTarget};
    if ~isfield(dRSA_PE, targetLabel)
        continue;
    end
    dRSAAll = {dRSA_PE.(targetLabel).position, dRSA_PE.(targetLabel).direction};
    figPEMatrices(iTarget) = figure( ...
        'Name', sprintf('PE dRSA matrices (%s)', targetLabel), ...
        'NumberTitle', 'off', ...
        'Visible', figVisibility);
    tiledlayout(2, numel(peModelNames), 'Padding', 'compact', 'TileSpacing', 'compact');
    rowAxes = gobjects(numel(dRSAAll), numel(peModelNames));
    for iRow = 1:numel(dRSAAll)
        for iModel = 1:numel(peModelNames)
            tileIdx = (iRow - 1) * numel(peModelNames) + iModel;
            nexttile(tileIdx);
            imagesc(timeSeconds, timeSeconds, dRSAAll{iRow}(:, :, iModel));
            set(gca, 'YDir', 'normal');
            axis image;
            if ~useCommonCbarLimits
                colorbar;
            end
            title(sprintf('%s | %s', local_pe_target_title(targetLabel), peModelNames{iModel}));
            % dRSA uses corr(modelRDM, neuralRDM): x = neural/data time, y = model time.
            xlabel(sprintf('Time in %s (s)', rowNames{iRow}));
            ylabel(sprintf('Time in %s (s)', peModelNames{iModel}));
            xticks(timeTicks);
            yticks(timeTicks);
            xticklabels(timeTickLabels);
            yticklabels(timeTickLabels);
            hold on;
            plot(timeSeconds, timeSeconds, 'w-', 'LineWidth', 1);
            local_overlay_time_guides(gca, guideTimes);
            hold off;
            if useCommonCbarLimits
                caxis(cbarLimits);
            end
            rowAxes(iRow, iModel) = gca;
        end
    end
    if useCommonCbarLimits
        for iRow = 1:numel(dRSAAll)
            cbarHandle = colorbar(rowAxes(iRow, end), 'Location', 'eastoutside');
            cbarHandle.Limits = cbarLimits;
        end
    end
end
end

function figHandle = local_plot_pe_paths(peDot1, sampleRateHz, titleText, figVisibility)
% LOCAL_PLOT_PE_PATHS Plot one-dot PE trajectories (observed minus predicted).
%
% Purpose:
%   Visualize one-dot trajectory-level PE using the same plotting style as
%   standard path diagnostics while removing any second-dot dependency.
%
% Inputs:
%   peDot1        : trials x 2 x time position PE for dot1.
%   sampleRateHz  : sampling rate used to label colorbar in seconds.
%   titleText     : figure-level title.
%   figVisibility : 'on' or 'off'.
%
% Output:
%   figHandle     : figure handle for export.
%
% Data flow:
%   PE paths -> one plot_paths subplot -> single PE_paths figure handle.

figHandle = figure('Name', char(titleText), 'NumberTitle', 'off', 'Visible', figVisibility);
tiledlayout(1, 1, 'Padding', 'compact', 'TileSpacing', 'compact');
ax1 = nexttile(1);
plot_paths(peDot1, 'ParentAxes', ax1, 'SavePlot', false, ...
    'Title', 'PE paths: dot1', 'SampleRateHz', sampleRateHz, ...
    'AxisLimits', []);
sgtitle(figHandle, char(titleText));
end

function titleText = local_pe_target_title(targetLabel)
% LOCAL_PE_TARGET_TITLE Map PE target field names to readable panel titles.
switch targetLabel
    case 'neuralPE'
        titleText = 'Neural target: PE';
    case 'neuralPredicted'
        titleText = 'Neural target: predicted';
    case 'neuralObserved'
        titleText = 'Neural target: observed';
    otherwise
        titleText = ['Neural target: ' targetLabel];
end
end

function [timeTicks, timeTickLabels] = local_build_midpoint_ticks(timeSeconds)
% LOCAL_BUILD_MIDPOINT_TICKS Build shared five-tick axes labels with midpoint marker.
%
% Inputs:
%   timeSeconds : 1xnTime vector defining the plotted time axis.
%
% Outputs:
%   timeTicks      : 1x5 numeric tick positions spanning the full axis range.
%   timeTickLabels : 1x5 cell labels with the midpoint replaced by 'M'.
%
% Data flow:
%   time axis endpoints -> evenly spaced 5-tick grid -> midpoint relabeling.
timeTicks = linspace(timeSeconds(1), timeSeconds(end), 5);
timeTickLabels = cellstr(compose('%.2f', timeTicks));
midTickIdx = ceil(numel(timeTicks) / 2);
timeTickLabels{midTickIdx} = 'M';
end

function eventFrames = local_resolve_plot_event_frames(meta, trialLen, deviantOnsetFallback)
% LOCAL_RESOLVE_PLOT_EVENT_FRAMES Resolve key occlusion event frames for plot guides.
%
% Inputs:
%   meta                : condition metadata from local_load_one_dot_condition_trials.
%   trialLen            : number of frames in the plotted stream before cuts.
%   deviantOnsetFallback: fallback fraction in [0,1] used only when
%                         reappearance metadata is unavailable.
%
% Output:
%   eventFrames : struct with fields
%       .fullDisappearanceFrame : 1-based occlusion_complete_frame (NaN if missing)
%       .reappearanceStartFrame : 1-based reappearance start frame
%       .reappearanceSource     : 'metadata' or 'fallback'.

eventFrames = struct( ...
    'fullDisappearanceFrame', nan, ...
    'reappearanceStartFrame', nan, ...
    'reappearanceSource', 'missing');

if isfield(meta, 'occlusionCompleteFrames') && ~isempty(meta.occlusionCompleteFrames)
    eventFrames.fullDisappearanceFrame = local_frame_vector_to_unique_frame( ...
        meta.occlusionCompleteFrames, trialLen, 'occlusion_complete_frame');
end

if isfield(meta, 'reappearanceStartFrames') && ~isempty(meta.reappearanceStartFrames)
    eventFrames.reappearanceStartFrame = local_frame_vector_to_unique_frame( ...
        meta.reappearanceStartFrames, trialLen, 'reappearance_start_frame');
    eventFrames.reappearanceSource = 'metadata';
else
    eventFrames.reappearanceStartFrame = local_resolve_cut_frame(meta, trialLen, deviantOnsetFallback);
    eventFrames.reappearanceSource = 'fallback';
end
end

function frameValue = local_frame_vector_to_unique_frame(frameVector, trialLen, frameLabel)
% LOCAL_FRAME_VECTOR_TO_UNIQUE_FRAME Convert optional per-trial frame vectors to one frame.
%
% Inputs:
%   frameVector : per-trial frame metadata vector with optional NaNs.
%   trialLen    : frame count used for clamping.
%   frameLabel  : label used in warning text when values vary.
%
% Output:
%   frameValue  : single clamped 1-based frame (NaN if no valid values).

frameValue = nan;
frames = double(frameVector(:));
frames = frames(isfinite(frames) & frames >= 1);
if isempty(frames)
    return;
end
frameValue = round(frames(1));
if any(round(frames) ~= round(frames(1)))
    warning(['%s is not constant across trials. Using first value (%d) for plot guides.'], ...
        frameLabel, frameValue);
end
frameValue = max(1, min(trialLen, frameValue));
end

function guideTimes = local_event_frames_to_seconds(eventFrames, startFrame, nTime, sampleRateHz)
% LOCAL_EVENT_FRAMES_TO_SECONDS Convert absolute event frames to plotted axis seconds.
%
% Inputs:
%   eventFrames   : struct from local_resolve_plot_event_frames.
%   startFrame    : 1-based first frame included in the current analysis window.
%   nTime         : number of time samples in the matrix axis.
%   sampleRateHz  : sampling rate for seconds conversion.
%
% Output:
%   guideTimes : struct with in-range guide times in seconds (NaN if out-of-range).

guideTimes = struct('fullDisappearanceSec', nan, 'reappearanceStartSec', nan);
if isempty(startFrame) || ~isscalar(startFrame) || ~isfinite(startFrame)
    startFrame = 1;
end
if isempty(nTime) || nTime < 1 || isempty(sampleRateHz) || sampleRateHz <= 0
    return;
end

guideTimes.fullDisappearanceSec = local_frame_to_window_seconds( ...
    eventFrames.fullDisappearanceFrame, startFrame, nTime, sampleRateHz);
guideTimes.reappearanceStartSec = local_frame_to_window_seconds( ...
    eventFrames.reappearanceStartFrame, startFrame, nTime, sampleRateHz);
end

function secValue = local_frame_to_window_seconds(frameValue, startFrame, nTime, sampleRateHz)
% LOCAL_FRAME_TO_WINDOW_SECONDS Convert one absolute frame to current-window seconds.
secValue = nan;
if ~isscalar(frameValue) || ~isfinite(frameValue)
    return;
end
relativeFrame = round(frameValue - startFrame + 1);
if relativeFrame < 1 || relativeFrame > nTime
    return;
end
secValue = (relativeFrame - 1) / sampleRateHz;
end

function local_overlay_time_guides(axHandle, guideTimes)
% LOCAL_OVERLAY_TIME_GUIDES Draw dotted horizontal/vertical event guides on matrix axes.
%
% Inputs:
%   axHandle   : target axes handle.
%   guideTimes : struct with fields fullDisappearanceSec and reappearanceStartSec.
%
% Visual convention:
%   - Full disappearance: black dotted crosshair.
%   - Reappearance start: cyan dotted crosshair.

if ~isgraphics(axHandle, 'axes') || ~isstruct(guideTimes)
    return;
end

if isfield(guideTimes, 'fullDisappearanceSec') && isfinite(guideTimes.fullDisappearanceSec)
    xline(axHandle, guideTimes.fullDisappearanceSec, ':', ...
        'Color', [0 0 0], 'LineWidth', 1.2, 'HandleVisibility', 'off');
    yline(axHandle, guideTimes.fullDisappearanceSec, ':', ...
        'Color', [0 0 0], 'LineWidth', 1.2, 'HandleVisibility', 'off');
end

if isfield(guideTimes, 'reappearanceStartSec') && isfinite(guideTimes.reappearanceStartSec)
    xline(axHandle, guideTimes.reappearanceStartSec, ':', ...
        'Color', [0 0.8 0.8], 'LineWidth', 1.2, 'HandleVisibility', 'off');
    yline(axHandle, guideTimes.reappearanceStartSec, ':', ...
        'Color', [0 0.8 0.8], 'LineWidth', 1.2, 'HandleVisibility', 'off');
end
end

function local_prepare_figure_for_export(figHandle)
% LOCAL_PREPARE_FIGURE_FOR_EXPORT Keep compact figure geometry before export.
%
% Inputs:
%   figHandle : figure handle prepared for saving.
%
% Data flow:
%   figure handle -> compact pixel size policy -> print/export-ready geometry.
%
% Notes:
%   - Avoids fullscreen maximization because square matrix panels (axis image)
%     create large central gaps on very wide canvases.
%   - Uses a fixed compact canvas for multi-panel tiled figures to keep
%     saved output consistent with on-screen previews.
if ~isgraphics(figHandle, 'figure')
    return;
end
set(figHandle, 'PaperPositionMode', 'auto');

oldUnits = figHandle.Units;
set(figHandle, 'Units', 'pixels');
currPos = get(figHandle, 'Position');
tiledLayouts = findobj(figHandle, 'Type', 'tiledlayout', '-depth', 1);
if ~isempty(tiledLayouts)
    panelAxes = findall(figHandle, 'Type', 'axes');
    if numel(panelAxes) >= 4
        currPos(3:4) = [1080, 920];
    else
        currPos(3:4) = [980, 760];
    end
else
    % Keep non-tiled figures compact but readable.
    currPos(3:4) = max(currPos(3:4), [940, 680]);
end
set(figHandle, 'Position', currPos);
set(figHandle, 'Units', oldUnits);
drawnow;
end

function local_scale_figure_text(figHandle, scaleFactor)
% LOCAL_SCALE_FIGURE_TEXT Scale axes/colorbar/title/label text in a figure.
% Data flow: figure handle -> axes/colorbar handles -> uniformly enlarged text.
if ~isgraphics(figHandle, 'figure') || ~isscalar(scaleFactor) || scaleFactor <= 0
    return;
end
allAxes = findall(figHandle, 'Type', 'axes');
for iAx = 1:numel(allAxes)
    ax = allAxes(iAx);
    if isprop(ax, 'FontSize')
        ax.FontSize = ax.FontSize * scaleFactor;
    end
end
allText = findall(figHandle, 'Type', 'text');
for iText = 1:numel(allText)
    txt = allText(iText);
    if isprop(txt, 'FontSize')
        txt.FontSize = txt.FontSize * scaleFactor;
    end
end
end

function local_print_existing_match_summary( ...
        resultsFile, participantNumber, inputCondition, dRSAtypeToRun, ...
        resampleSubsamples, resampleIterations, ...
        resampleSubsampleCount, resampleWithReplacement, ...
        usePredictedModels, plotSampleRateHz, cutPostDev, cutPostDevPlot, deviantOnset, ...
        currentPCRStrategy, existingMeta)
% LOCAL_PRINT_EXISTING_MATCH_SUMMARY Print parameter-by-parameter reuse summary.
% Data flow: current config + existing metadata -> one-line comparison per parameter.
fprintf('\nExisting results file found:\n  %s\n', resultsFile);

existingParticipant = [];
existingCondition = [];
existingType = [];
existingResample = [];
existingResampleIter = [];
existingResampleCount = [];
existingResampleReplacement = [];
existingUsePredicted = [];
existingFs = [];
existingCutPostDev = [];
existingCutPostDevPlot = [];
existingDeviantOnset = [];
existingPCRStrategy = [];

if isfield(existingMeta, 'repro')
    repro = existingMeta.repro;
    if isfield(repro, 'participantNumber')
        existingParticipant = repro.participantNumber;
    end
    if isfield(repro, 'inputCondition')
        existingCondition = repro.inputCondition;
    end
    if isfield(repro, 'resampleSubsamples')
        existingResample = repro.resampleSubsamples;
    end
    if isfield(repro, 'resampleIterations')
        existingResampleIter = repro.resampleIterations;
    end
    if isfield(repro, 'resampleSubsampleCount')
        existingResampleCount = repro.resampleSubsampleCount;
    end
    if isfield(repro, 'resampleWithReplacement')
        existingResampleReplacement = repro.resampleWithReplacement;
    end
    if isfield(repro, 'nModels')
        existingUsePredicted = repro.nModels > 2;
    end
    if isfield(repro, 'cutPostDev')
        existingCutPostDev = repro.cutPostDev;
    end
    if isfield(repro, 'cutPostDevPlot')
        existingCutPostDevPlot = repro.cutPostDevPlot;
    end
    if isfield(repro, 'deviantOnset')
        existingDeviantOnset = repro.deviantOnset;
    end
    if isfield(repro, 'pcrRegressStrategy')
        existingPCRStrategy = repro.pcrRegressStrategy;
    end
    if isfield(repro, 'paramsCore')
        if isfield(repro.paramsCore, 'dRSAtype')
            existingType = repro.paramsCore.dRSAtype;
        end
        if isfield(repro.paramsCore, 'fs')
            existingFs = repro.paramsCore.fs;
        end
        if isempty(existingPCRStrategy) && isfield(repro.paramsCore, 'PCR') && ...
                isfield(repro.paramsCore.PCR, 'RegressStrategy')
            existingPCRStrategy = repro.paramsCore.PCR.RegressStrategy;
        end
    end
end
if isempty(existingType) && isfield(existingMeta, 'params') && isfield(existingMeta.params, 'dRSAtype')
    existingType = existingMeta.params.dRSAtype;
end
if isempty(existingFs) && isfield(existingMeta, 'params') && isfield(existingMeta.params, 'fs')
    existingFs = existingMeta.params.fs;
end
if isempty(existingPCRStrategy) && isfield(existingMeta, 'params') && ...
        isfield(existingMeta.params, 'PCR') && ...
        isfield(existingMeta.params.PCR, 'RegressStrategy')
    existingPCRStrategy = existingMeta.params.PCR.RegressStrategy;
end

local_print_match_line('participantNumber', participantNumber, existingParticipant);
local_print_match_line('inputCondition', inputCondition, existingCondition);
local_print_match_line('dRSAtypeToRun', dRSAtypeToRun, existingType);
local_print_match_line('resampleSubsamples', resampleSubsamples, existingResample);
local_print_match_line('resampleIterations', resampleIterations, existingResampleIter);
local_print_match_line('resampleSubsampleCount', resampleSubsampleCount, existingResampleCount);
local_print_match_line('resampleWithReplacement', resampleWithReplacement, existingResampleReplacement);
local_print_match_line('usePredictedModels', usePredictedModels, existingUsePredicted);
local_print_match_line('plotSampleRateHz', plotSampleRateHz, existingFs);
local_print_match_line('cutPostDev', cutPostDev, existingCutPostDev);
local_print_match_line('cutPostDevPlot', cutPostDevPlot, existingCutPostDevPlot);
local_print_match_line('deviantOnset', deviantOnset, existingDeviantOnset);
if strcmpi(dRSAtypeToRun, 'PCR')
    local_print_match_line('params.PCR.RegressStrategy', currentPCRStrategy, existingPCRStrategy);
end
end

function local_print_match_line(paramName, currentValue, existingValue)
% LOCAL_PRINT_MATCH_LINE Print one parameter comparison line.
isExistingMissing = isempty(existingValue);
isMatch = ~isExistingMissing && isequaln(currentValue, existingValue);
statusLabel = 'MISMATCH';
if isExistingMissing
    statusLabel = 'MISSING';
elseif isMatch
    statusLabel = 'MATCH';
end
fprintf('  - %-24s current=%-10s existing=%-10s [%s]\n', ...
    paramName, local_value_to_string(currentValue), ...
    local_value_to_string(existingValue), statusLabel);
end

function out = local_value_to_string(in)
% LOCAL_VALUE_TO_STRING Convert scalar/cell/string values to compact text.
if isempty(in)
    out = 'N/A';
elseif islogical(in) && isscalar(in)
    out = mat2str(in);
elseif isnumeric(in) && isscalar(in)
    out = num2str(in);
elseif ischar(in)
    out = in;
elseif isstring(in) && isscalar(in)
    out = char(in);
elseif iscell(in) && isscalar(in)
    out = local_value_to_string(in{1});
else
    out = mat2str(in);
end
end

function action = local_resolve_existing_results_action(existingResultsAction)
% LOCAL_RESOLVE_EXISTING_RESULTS_ACTION Resolve interactive vs configured reuse action.
%
% Inputs:
%   existingResultsAction : [] for interactive prompt, or scalar 1/2/3.
%
% Outputs:
%   action:
%     1 = load existing dataset + replot
%     2 = full rerun + overwrite dataset and plots
%     3 = just error out
if isempty(existingResultsAction)
    action = local_prompt_existing_results_action();
    return;
end
action = existingResultsAction;
end

function userChoice = local_prompt_existing_results_action()
% LOCAL_PROMPT_EXISTING_RESULTS_ACTION Ask whether to reuse, rerun, or stop.
% Output:
%   1 = load existing and replot
%   2 = rerun and overwrite all outputs
%   3 = just error out
userChoice = 0;
while ~ismember(userChoice, [1, 2, 3])
    userInput = input([ ...
        'Select action: (1) load existing dataset + replot (overwrite plots), ', ...
        '(2) rerun + overwrite dataset and plots, ', ...
        '(3) just error out: '], 's');
    userChoice = str2double(strtrim(userInput));
end
end

function [pathsCut, cutFrame] = local_cut_from_frame(paths, cutFrame)
% LOCAL_CUT_FROM_FRAME Slice trial paths from a provided 1-based frame index.
%
% Inputs:
%   paths    : trials x features x time tensor.
%   cutFrame : desired 1-based start frame.
%
% Outputs:
%   pathsCut : paths(:, :, cutFrame:end).
%   cutFrame : validated/clamped frame index actually used.
if isempty(paths)
    pathsCut = paths;
    cutFrame = [];
    return;
end
trialLen = size(paths, 3);
if trialLen < 1
    pathsCut = paths;
    cutFrame = [];
    return;
end
if isempty(cutFrame) || ~isscalar(cutFrame) || ~isfinite(cutFrame)
    cutFrame = 1;
end
cutFrame = round(cutFrame);
cutFrame = max(1, min(trialLen, cutFrame));
pathsCut = paths(:, :, cutFrame:end);
end

function cutFrame = local_resolve_cut_frame(meta, trialLen, deviantOnsetFallback)
% LOCAL_RESOLVE_CUT_FRAME Resolve PE cut frame from metadata or fallback fraction.
%
% Priority:
%   1) unique reappearance_start_frame metadata from condition trials.
%   2) fallback fractional onset (deviantOnsetFallback).
if isfield(meta, 'reappearanceStartFrames') && ~isempty(meta.reappearanceStartFrames)
    frames = double(meta.reappearanceStartFrames(:));
    frames = frames(isfinite(frames) & frames >= 1);
    if ~isempty(frames)
        cutFrame = round(frames(1));
        if any(round(frames) ~= round(frames(1)))
            warning(['reappearance_start_frame is not constant across trials. ' ...
                'Using first value (%d) for PE cut.'], cutFrame);
        end
        cutFrame = max(1, min(trialLen, cutFrame));
        return;
    end
end

if isempty(deviantOnsetFallback) || ~isscalar(deviantOnsetFallback) || ...
        ~isfinite(deviantOnsetFallback) || deviantOnsetFallback < 0 || deviantOnsetFallback > 1
    deviantOnsetFallback = 0.5;
end
cutFrame = round(deviantOnsetFallback * trialLen);
cutFrame = max(1, min(trialLen, cutFrame));
end

function [dot1Trials, meta] = local_load_one_dot_condition_trials( ...
        rawInputFile, conditionLabel, centerRelativeRectSize, allowMissingCondition)
% LOCAL_LOAD_ONE_DOT_CONDITION_TRIALS Load center-relative one-dot trials for one condition.
%
% Usage examples:
%   [always, meta] = local_load_one_dot_condition_trials( ...
%       'experiment/input_files/MovDot_Sub70.mat', 'always_visible', [], false);
%   [nondev, meta] = local_load_one_dot_condition_trials( ...
%       'experiment/input_files/MovDot_Sub70.mat', 'occluded_nondeviant', [], false);
%   [predDev, meta] = local_load_one_dot_condition_trials( ...
%       'experiment/input_files/MovDot_Sub70_predicted.mat', 'occluded_deviant', [], true);
%
% Inputs:
%   rawInputFile         : file path to MovDot_SubXX.mat or MovDot_SubXX_predicted.mat.
%   conditionLabel       : 'always_visible', 'occluded_nondeviant', or
%                          'occluded_deviant'.
%   centerRelativeRectSize : optional [width height] override for recentering.
%   allowMissingCondition: true to allow empty condition results (returns []).
%
% Outputs:
%   dot1Trials : trials x 2 x time center-relative one-dot positions.
%   meta       : struct with source and parsing metadata.
%
% One-dot enforcement:
%   This helper accepts only xy column count == 2. If xy has >= 4 columns,
%   the input appears to be two-dot and this script errors by design.
%
% Data flow:
%   source MAT -> xy field selection -> valid trial filter -> condition split
%   -> one-dot column validation -> center shift -> output tensor.

if ~isfile(rawInputFile)
    error('Input file not found: %s', rawInputFile);
end

sourceData = load(rawInputFile);
if isfield(sourceData, 'xySeqs')
    xyField = 'xySeqs';
elseif isfield(sourceData, 'xySeqsPredicted')
    xyField = 'xySeqsPredicted';
else
    error('Expected xySeqs or xySeqsPredicted in %s.', rawInputFile);
end

allTrials = sourceData.(xyField)(:);
if isempty(allTrials) || ~isfield(allTrials, 'xy')
    error('Input %s has no usable xy trials in field %s.', rawInputFile, xyField);
end

% Keep numeric non-empty xy entries with at least x/y columns.
validMask = arrayfun(@(s) isnumeric(s.xy) && ~isempty(s.xy) && ...
    size(s.xy, 1) > 0 && size(s.xy, 2) >= 2, allTrials);
allTrials = allTrials(validMask);
if isempty(allTrials)
    error('No valid xy trials found in %s.', rawInputFile);
end

xyColumnCounts = arrayfun(@(s) size(s.xy, 2), allTrials);
if any(xyColumnCounts >= 4)
    error(['One-dot-only script detected multi-dot xy format in %s (xy columns >= 4). ' ...
        'Use PE_simulation_diff.m for two-dot inputs.'], rawInputFile);
end
if any(xyColumnCounts ~= 2)
    error('One-dot-only script requires xy columns [x y]. Detected columns: %s in %s.', ...
        mat2str(unique(xyColumnCounts)), rawInputFile);
end
xyColumnCount = 2;

conditionLabel = lower(char(conditionLabel));
condValues = [];
if isfield(allTrials, 'condition')
    condValues = arrayfun(@(s) s.condition, allTrials);
end

labelValues = strings(numel(allTrials), 1);
if isfield(allTrials, 'condition_label')
    labelValues = arrayfun(@(s) string(s.condition_label), allTrials, 'UniformOutput', true);
end

switch conditionLabel
    case 'always_visible'
        if any(strlength(labelValues) > 0)
            conditionMask = strcmp(labelValues, 'always_visible');
        else
            if isempty(condValues)
                error('No condition_label or condition field in %s.', rawInputFile);
            end
            conditionMask = (condValues < 0);
        end
    case 'occluded_nondeviant'
        if any(strlength(labelValues) > 0)
            conditionMask = strcmp(labelValues, 'occluded_nondeviant');
        else
            if isempty(condValues)
                error('No condition_label or condition field in %s.', rawInputFile);
            end
            conditionMask = (condValues == 0);
        end
    case 'occluded_deviant'
        if any(strlength(labelValues) > 0)
            conditionMask = strcmp(labelValues, 'occluded_deviant') | ...
                strcmp(labelValues, 'occluded_deviant_predicted');
        else
            if isempty(condValues)
                error('No condition_label or condition field in %s.', rawInputFile);
            end
            conditionMask = (condValues > 0);
        end
    otherwise
        error('Unsupported condition label: %s', conditionLabel);
end

condTrials = allTrials(conditionMask);
if isempty(condTrials)
    if allowMissingCondition
        dot1Trials = zeros(0, 2, 0);
        meta = struct( ...
            'sourceFile', rawInputFile, ...
            'xyField', xyField, ...
            'xyColumnCount', xyColumnCount, ...
            'conditionLabel', conditionLabel, ...
            'rectSize', [], ...
            'occlusionCompleteFrames', [], ...
            'reappearanceStartFrames', [], ...
            'sequenceValues', []);
        return;
    end
    error('No %s one-dot trials found in %s (%s).', conditionLabel, rawInputFile, xyField);
end

frameCounts = arrayfun(@(s) size(s.xy, 1), condTrials);
if any(frameCounts ~= frameCounts(1))
    error('Inconsistent frame counts in %s condition for %s.', conditionLabel, rawInputFile);
end

nTrials = numel(condTrials);
nFrames = frameCounts(1);
dot1Trials = zeros(nTrials, 2, nFrames);
for iTrial = 1:nTrials
    xy = double(condTrials(iTrial).xy);
    dot1Trials(iTrial, 1, :) = reshape(xy(:, 1), 1, 1, []);
    dot1Trials(iTrial, 2, :) = reshape(xy(:, 2), 1, 1, []);
end

% Center-relative conversion:
% coordinates in input files are absolute [0..rectSize] visual degrees.
if ~isempty(centerRelativeRectSize)
    rectSizeToUse = double(centerRelativeRectSize(:)');
elseif isfield(sourceData, 'Cfg') && isfield(sourceData.Cfg, 'rectSize')
    rectSizeToUse = double(sourceData.Cfg.rectSize(:)');
else
    error(['Center-relative conversion requires Cfg.rectSize or centerRelativeRectSize override. ' ...
        'Missing in %s.'], rawInputFile);
end
if numel(rectSizeToUse) ~= 2
    error('Rect size must be [width height] in %s.', rawInputFile);
end
centerShift = reshape(rectSizeToUse ./ 2, [1, 2, 1]);
dot1Trials = bsxfun(@minus, dot1Trials, centerShift);

meta = struct( ...
    'sourceFile', rawInputFile, ...
    'xyField', xyField, ...
    'xyColumnCount', xyColumnCount, ...
    'conditionLabel', conditionLabel, ...
    'rectSize', rectSizeToUse, ...
    'occlusionCompleteFrames', local_extract_optional_frame_vector(condTrials, 'occlusion_complete_frame'), ...
    'reappearanceStartFrames', local_extract_optional_frame_vector(condTrials, 'reappearance_start_frame'), ...
    'sequenceValues', local_extract_optional_sequence_vector(condTrials));
end

function frameVector = local_extract_optional_frame_vector(trials, fieldName)
% LOCAL_EXTRACT_OPTIONAL_FRAME_VECTOR Extract optional integer frame metadata.
%
% Inputs:
%   trials    : struct array of condition trials.
%   fieldName : metadata field to read from each trial.
%
% Output:
%   frameVector : column vector with NaN for missing/invalid entries.
nTrials = numel(trials);
frameVector = nan(nTrials, 1);
for iTrial = 1:nTrials
    if isfield(trials(iTrial), fieldName)
        value = trials(iTrial).(fieldName);
        if ~isempty(value) && isfinite(double(value))
            frameVector(iTrial) = round(double(value));
        end
    end
end
end

function sequenceVector = local_extract_optional_sequence_vector(trials)
% LOCAL_EXTRACT_OPTIONAL_SEQUENCE_VECTOR Extract sequence IDs per trial.
%
% Inputs:
%   trials : struct array of condition trials.
%
% Output:
%   sequenceVector : column vector with NaN for missing/invalid entries.
nTrials = numel(trials);
sequenceVector = nan(nTrials, 1);
for iTrial = 1:nTrials
    if isfield(trials(iTrial), 'sequence')
        value = trials(iTrial).sequence;
        if ~isempty(value) && isfinite(double(value))
            sequenceVector(iTrial) = round(double(value));
        end
    end
end
end

function [alwaysSample, nondeviantSample, deviantSample] = local_sample_same_trials_across_conditions( ...
        alwaysPaths, alwaysMeta, nondeviantPaths, nondeviantMeta, deviantPaths, deviantMeta, sampleCount)
% LOCAL_SAMPLE_SAME_TRIALS_ACROSS_CONDITIONS Sample matching trials across three conditions.
%
% Inputs:
%   alwaysPaths     : trials x 2 x time always-visible paths.
%   alwaysMeta      : metadata struct for always-visible trials.
%   nondeviantPaths : trials x 2 x time occluded nondeviant paths.
%   nondeviantMeta  : metadata struct for occluded nondeviant trials.
%   deviantPaths    : trials x 2 x time occluded deviant paths.
%   deviantMeta     : metadata struct for occluded deviant trials.
%   sampleCount     : max number of shared trials to sample.
%
% Outputs:
%   alwaysSample, nondeviantSample, deviantSample : sampled path tensors
%   using the same trial identity across all three conditions.
%
% Data flow:
%   condition arrays + sequence metadata -> shared sequence IDs (preferred)
%   -> matched index draws -> sampled arrays.

if isempty(alwaysPaths) || isempty(nondeviantPaths) || isempty(deviantPaths)
    error('Cannot sample shared trials: one or more condition arrays are empty.');
end

nAlways = size(alwaysPaths, 1);
nNondev = size(nondeviantPaths, 1);
nDev = size(deviantPaths, 1);

seqAlways = [];
seqNondev = [];
seqDev = [];
if isfield(alwaysMeta, 'sequenceValues')
    seqAlways = alwaysMeta.sequenceValues(:);
end
if isfield(nondeviantMeta, 'sequenceValues')
    seqNondev = nondeviantMeta.sequenceValues(:);
end
if isfield(deviantMeta, 'sequenceValues')
    seqDev = deviantMeta.sequenceValues(:);
end

useSequenceMatching = ...
    numel(seqAlways) == nAlways && numel(seqNondev) == nNondev && numel(seqDev) == nDev && ...
    all(isfinite(seqAlways)) && all(isfinite(seqNondev)) && all(isfinite(seqDev));

if useSequenceMatching
    commonSeq = intersect(intersect(unique(seqAlways), unique(seqNondev)), unique(seqDev));
    if ~isempty(commonSeq)
        nPick = min(sampleCount, numel(commonSeq));
        drawSeq = commonSeq(randperm(numel(commonSeq), nPick));
        idxAlways = local_indices_for_sequences(seqAlways, drawSeq);
        idxNondev = local_indices_for_sequences(seqNondev, drawSeq);
        idxDev = local_indices_for_sequences(seqDev, drawSeq);
        if all(idxAlways > 0) && all(idxNondev > 0) && all(idxDev > 0)
            alwaysSample = alwaysPaths(idxAlways, :, :);
            nondeviantSample = nondeviantPaths(idxNondev, :, :);
            deviantSample = deviantPaths(idxDev, :, :);
            return;
        end
    end
end

% Fallback when sequence metadata is absent/inconsistent: shared index draw.
nCommon = min([nAlways, nNondev, nDev]);
if nCommon < 1
    error('No shared trials available for plotting.');
end
nPick = min(sampleCount, nCommon);
drawIdx = randperm(nCommon, nPick);
alwaysSample = alwaysPaths(drawIdx, :, :);
nondeviantSample = nondeviantPaths(drawIdx, :, :);
deviantSample = deviantPaths(drawIdx, :, :);
end

function idx = local_indices_for_sequences(sequenceVector, sequenceList)
% LOCAL_INDICES_FOR_SEQUENCES Resolve first matching row index for each sequence ID.
idx = zeros(1, numel(sequenceList));
for i = 1:numel(sequenceList)
    match = find(sequenceVector == sequenceList(i), 1, 'first');
    if isempty(match)
        idx(i) = 0;
    else
        idx(i) = match;
    end
end
end

function axisLimits = local_compute_shared_axis_limits(pathCell)
% LOCAL_COMPUTE_SHARED_AXIS_LIMITS Compute a shared [xmin xmax ymin ymax] box.
%
% Inputs:
%   pathCell : cell array of trials x 2 x time path tensors.
%
% Output:
%   axisLimits : 1x4 numeric vector with a small padding margin.
xMin = inf;
xMax = -inf;
yMin = inf;
yMax = -inf;

for i = 1:numel(pathCell)
    paths = pathCell{i};
    if isempty(paths)
        continue;
    end
    xVals = reshape(paths(:, 1, :), [], 1);
    yVals = reshape(paths(:, 2, :), [], 1);
    xMin = min(xMin, min(xVals));
    xMax = max(xMax, max(xVals));
    yMin = min(yMin, min(yVals));
    yMax = max(yMax, max(yVals));
end

if ~isfinite(xMin) || ~isfinite(xMax) || ~isfinite(yMin) || ~isfinite(yMax)
    axisLimits = [];
    return;
end

xRange = max(eps, xMax - xMin);
yRange = max(eps, yMax - yMin);
xPad = 0.05 * xRange;
yPad = 0.05 * yRange;
axisLimits = [xMin - xPad, xMax + xPad, yMin - yPad, yMax + yPad];
end

function figHandle = local_plot_all_condition_paths_onedot( ...
        alwaysVisiblePaths, nondeviantPaths, deviantPaths, axisLimits, sampleRateHz, titleText, figVisibility)
% LOCAL_PLOT_ALL_CONDITION_PATHS_ONEDOT Plot sampled one-dot paths for all three conditions.
%
% Inputs:
%   alwaysVisiblePaths : trials x 2 x time sampled always-visible paths.
%   nondeviantPaths    : trials x 2 x time sampled occluded nondeviant paths.
%   deviantPaths       : trials x 2 x time sampled occluded deviant paths.
%   axisLimits         : shared [xmin xmax ymin ymax] for all condition axes.
%   sampleRateHz       : sampling rate for seconds colorbar.
%   titleText          : figure-level title.
%   figVisibility      : 'on' or 'off'.
%
% Output:
%   figHandle          : figure handle ready for export.
%
% Data flow:
%   matched sampled arrays -> shared-axis three-panel path figure.

figHandle = figure('Name', char(titleText), 'NumberTitle', 'off', 'Visible', figVisibility);
tiledlayout(1, 3, 'Padding', 'compact', 'TileSpacing', 'compact');

ax1 = nexttile(1);
plot_paths(alwaysVisiblePaths, 'ParentAxes', ax1, 'SavePlot', false, ...
    'Title', 'Always visible: dot1', 'SampleRateHz', sampleRateHz, ...
    'AxisLimits', axisLimits);

ax2 = nexttile(2);
plot_paths(nondeviantPaths, 'ParentAxes', ax2, 'SavePlot', false, ...
    'Title', 'Occluded nondeviant: dot1', 'SampleRateHz', sampleRateHz, ...
    'AxisLimits', axisLimits);

ax3 = nexttile(3);
plot_paths(deviantPaths, 'ParentAxes', ax3, 'SavePlot', false, ...
    'Title', 'Occluded deviant: dot1', 'SampleRateHz', sampleRateHz, ...
    'AxisLimits', axisLimits);

sgtitle(figHandle, char(titleText));
end

function strategyTag = local_get_pcr_strategy_tag(params)
% LOCAL_GET_PCR_STRATEGY_TAG Build filename-safe suffix for PCR strategy.
%
% Inputs:
%   params: run parameter struct with optional params.PCR.RegressStrategy.
%
% Output:
%   strategyTag:
%       'baseline' for legacy PCR strategy, or compact alphanumeric strategy
%       tag for alternative backends.
%
% Data flow:
%   params.PCR.RegressStrategy -> normalized lowercase label -> filename-safe tag.
strategyName = 'baseline_pcr_border';
if isfield(params, 'PCR') && isstruct(params.PCR) && ...
        isfield(params.PCR, 'RegressStrategy') && ~isempty(params.PCR.RegressStrategy)
    strategyName = lower(char(params.PCR.RegressStrategy));
end

if strcmp(strategyName, 'baseline_pcr_border')
    strategyTag = 'baseline';
elseif strcmp(strategyName, 'ridge_full_autocorr')
    strategyTag = 'ridgeFullAuto';
elseif strcmp(strategyName, 'ridge_tapered_autocorr')
    strategyTag = 'ridgeTaperedAuto';
elseif strcmp(strategyName, 'ar1_prewhite_ridge')
    strategyTag = 'ar1PrewhiteRidge';
else
    % Fallback keeps unknown custom strategies usable while sanitizing for paths.
    strategyTag = regexprep(strategyName, '[^a-zA-Z0-9]', '');
    if isempty(strategyTag)
        strategyTag = 'custom';
    end
end
end

function modelNames = local_default_model_names(nModels)
% LOCAL_DEFAULT_MODEL_NAMES Provide fallback names if metadata is missing.
baseNames = {'position dot1', 'direction dot1', ...
    'predicted position dot1', 'predicted direction dot1'};
if nModels <= numel(baseNames)
    modelNames = baseNames(1:nModels);
    return;
end
modelNames = cell(1, nModels);
for iModel = 1:nModels
    modelNames{iModel} = sprintf('model %d', iModel);
end
end
